### DISCUSSION TITLE
Installing AWS Infrastructure Provider with Cluster API Operator

### DISCUSSION THREAD

**Discussion by d3bt3ch** [kubernetes-sigs/cluster-api-provider-aws#4419] [Q&A]
I am using `cluster-api-operator` to provision the management cluster. Can someone guide me on the `ConfigMap` and `Secret` I need to create to install the `aws` provider. I tried creating a secret with `AWS_B64ENCODED_CREDENTIALS` but the cluster-api-operator pod log complains with reconciliation failure.

Here is the configuration

```
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: capa-system
type: Opaque
data:
  AWS_B64ENCODED_CREDENTIALS: xxxxxx
  GITHUB_TOKEN: xxxxxx
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: aws
 namespace: capa-system
spec:
  version: v2.2.1
  secretName: aws-secret
  secretNamespace: capa-system
```
