### DISCUSSION TITLE
Initial Support for Dedicated Hosts

### DISCUSSION THREAD

**Discussion by faermanj** [kubernetes-sigs/cluster-api-provider-aws#5213] [Ideas]
Hello fellows,

I'd lilke to propose we build support the dedicated hosts feature of EC2, as that is relevant to users under strict licesing compliance, and other security-related motivations. From the EC2 API perspective, it's a matter of setting the proper placement arguments, HostID and Affinity.

More info about dedicated hosts: 
* https://aws.amazon.com/ec2/dedicated-hosts/
* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launching-dedicated-hosts-instances.html

So I believe we should discuss how that could look like in the spec?

I mean something like this perhaps:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: jufaerma_us-east-1
      dedicatedHosts:
          - id: host-id-xxxxx
            affinity: Host
          - id: host-id-yyyyy
            affinity: Default
          - id: host-id-zzzzz
            affinity: Default
```
I'm not sure how to map replicas to hosts though...

What do you think?
