### ISSUE TITLE
Cannot access workload cluster with admin config

### ISSUE THREAD

**Issue by chris-cmsoft** [kubernetes-sigs/cluster-api-provider-aws#1106]
/kind bug

**What steps did you take and what happened:**

Applied a workload cluster which created correctly.
If I access the cluster from the control plane, the admin conf works perfectly.
If I copy the admin config to local:
```
error: You must be logged in to the server (Unauthorized)
```
If I read the kubeconfig from the secrets created for that cluster, I get the same error

Endpoint is correctly setup for LB

**What did you expect to happen:**

Expect to be able to call K8S APi from external

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.3.7
- Kubernetes version: (use `kubectl version`):  v1.15.0, cluster 1.14.4
- OS (e.g. from `/etc/os-release`):  Darwin 10.14.6

Applied workload cluster:
```
---
# Source: basic/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: basic-w-deploy-cluster
---
# Source: basic/templates/cluster.yaml
# Represents the whole workload cluster state
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: basic-w-deploy
  namespace: basic-w-deploy-cluster
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]

    pods:
      cidrBlocks: ["192.168.0.0/16"]

    serviceDomain: "cluster.local"
  providerSpec:
    value:
      apiVersion: "awsprovider/v1alpha1"
      kind: "AWSClusterProviderSpec"
      region: eu-west-1
      sshKeyName: default

---
# Source: basic/templates/control-plane-machine.yaml
# A Machine defines a Node in Kubernetes
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: basic-w-deploy-controlplane-0
  namespace: basic-w-deploy-cluster
  labels:
    cluster.k8s.io/cluster-name: "basic-w-deploy"
    set: controlplane
spec:
  versions:
    kubelet: v1.14.4
    controlPlane: v1.14.4
  providerSpec:
    value:
      apiVersion: awsprovider/v1alpha1
      kind: AWSMachineProviderSpec
      instanceType: "t2.medium"
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      keyName: "default"

---
# Source: basic/templates/machine-deployment.yaml
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: basic-w-deploy-machinedeployment
  namespace: basic-w-deploy-cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: basic-w-deploy
      set: node
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: basic-w-deploy
        set: node
    spec:
      versions:
        kubelet: v1.14.4
      providerSpec:
        value:
          apiVersion: awsprovider/v1alpha1
          kind: AWSMachineProviderSpec
          instanceType: "t2.medium"
          iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
          keyName: "default"
```
