### ISSUE TITLE
Cannot create two public subnets

### ISSUE THREAD

**Issue by liztio** [kubernetes-sigs/cluster-api-provider-aws#1173]
/kind bug

**What steps did you take and what happened:**

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: AWSCluster
metadata:
  name: cloudsdale
  namespace: default
spec:
  region: us-east-1
  sshKeyName: default
  networkSpec:
    subnets:
      - cidrBlock: "10.0.1.0/24"
        isPublic: true
        availabilityZone: "us-east-1a"
      - cidrBlock: "10.0.2.0/24"
        isPublic: true
        availabilityZone: "us-east-1b"
      - cidrBlock: "10.0.0.0/24"
        isPublic: false
        availabilityZone: "us-east-1a"
```

Creating multiple subnets allocates multiple NAT gateways, but they will both try to use the same EIP: 
![image](https://user-images.githubusercontent.com/33235082/66242652-0308b880-e6d0-11e9-9238-45b23420d442.png)

Only one elastic IP is ever created: https://github.com/liztio/cluster-api-provider-aws/blob/d3c1b7f/pkg/cloud/services/ec2/natgateways.go#L163

**What did you expect to happen:**

Two EIPs should've been allocated for two NAT gateways

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Came up as part of testing the ALB ingress controller for #1142, which requires two subnets. 

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by luigi-riefolo** [comment]
@liztio I can help with this
/assign

**Comment by aaroniscode** [comment]
@liztio Just taking a quick look at this. Shouldn't the public subnets use the Internet Gateway and only the private subnets have a NAT gateway in them?  Your example above only has one private subnet so I would only expect one NAT gateway.

Am I looking at this wrong?

**Comment by vincepri** [comment]
You'll need to have at least 1 private subnet for each 1 public subnet for each distinct AZ

**Comment by vincepri** [comment]
This issue is a good candidate for validation webhooks :)

**Comment by luigi-riefolo** [comment]
@vincepri do you mean that I need to add webhook validation for the changes?

**Comment by luigi-riefolo** [comment]
@vincepri running `make create-cluster-management` causes this error:

```
kubectl logs -n capa-system    pod/capa-controller-manager-b5cb99d4d-zpbwn   
I1027 14:23:33.081254       1 listener.go:40] controller-runtime/metrics "msg"="metrics server is starting to listen"  "addr"=":8080"
I1027 14:23:33.082159       1 controller.go:121] controller-runtime/controller "msg"="Starting EventSource"  "controller"="awsmachine" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"ami":{}},"status":{"ready":false}}}
E1027 14:23:34.927232       1 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"AWSMachine\" in version \"infrastructure.cluster.x-k8s.io/v1alpha3\""  "kind"={"Group":"infrastructure.cluster.x-k8s.io","Kind":"AWSMachine"}
E1027 14:23:34.927274       1 main.go:172] setup "msg"="unable to create controller" "error"="no matches for kind \"AWSMachine\" in version \"infrastructure.cluster.x-k8s.io/v1alpha3\""  "controller"="AWSMachine"
```

I'm using the master branch, any idea why this is happening?

**Comment by vincepri** [comment]
master might be broken given that we're starting to work on v1alpha3, @liztio can you confirm if this bug was found in v1alpha2?

**Comment by detiber** [comment]
master is currently functional based on the recent fixes to the e2e testing: https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-cluster-api-provider-aws#periodic-e2e-release-0-4 (that isn't to say that it is bug free)

**Comment by luigi-riefolo** [comment]
```validatingwebhookconfiguration.admissionregistration.k8s.io/capa-validating-webhook-configuration created
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
Makefile:310: recipe for target 'create-cluster-management' failed
```

that was in the latest master. If it's still broken, could you please just tell me a stable branch?

**Comment by vincepri** [comment]
`release-0.4` is the v1alpha2 one

**Comment by luigi-riefolo** [comment]
thanks @vincepri but in that branch I'm getting:
```
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"
unable to recognize "examples/_out/provider-components.yaml": no matches for kind "Issuer" in version "certmanager.k8s.io/v1alpha1"
Makefile:310: recipe for target 'create-cluster-management' failed
make: *** [create-cluster-management] Error 1
```

any idea?

**Comment by vincepri** [comment]
@luigi-riefolo Can you open a different issue for that error with the steps to reproduce it? It doesn’t seem related to this bug

**Comment by luigi-riefolo** [comment]
@vincepri sure, but what about this issue?

**Comment by luigi-riefolo** [comment]
@liztio I cannot reproduce the issue. This is what I get when declaring two public subnets:
```
  networkSpec:
    subnets:
      - cidrBlock: "10.0.1.0/24"
        isPublic: true
        availabilityZone: "eu-west-2a"
      - cidrBlock: "10.0.2.0/24"
        isPublic: true
        availabilityZone: "eu-west-2b"
      - cidrBlock: "10.0.0.0/24"
        isPublic: false
        availabilityZone: "eu-west-2a"
```

<img width="1439" alt="Screenshot 2019-12-01 at 15 01 03" src="https://user-images.githubusercontent.com/4227453/69915876-eed10580-144b-11ea-8d42-66c7375f9b10.png">
<img width="1439" alt="Screenshot 2019-12-01 at 15 01 52" src="https://user-images.githubusercontent.com/4227453/69915877-eed10580-144b-11ea-8f31-1a02232f1927.png">

@vincepri should we close this issue?
