### ISSUE TITLE
[Umbrella] Support for EKS

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1534]
/kind feature

**Describe the solution you'd like**
I'd like to see the ability to create/manage EKS clusters using Cluster API. This is the parent issue for implementing EKS. There are sub tasks and issues listed below for implementation of specific functionality.

**Anything else you would like to add:**
This comes up quite a bit in discussions with customers around capi. Especially in hybrid on-prem/cloud type environments.

This relates to https://github.com/kubernetes-sigs/cluster-api/issues/980 and also the associated proposal https://github.com/kubernetes-sigs/cluster-api/pull/2045

### Tasks:
- [x] Refactor ClusterScope and services that depend on it - issue #1796 (Now merged to main)
- [x] EKS controlplane support - issue #1787 
- [x] EKS AMI lookup support - issue #1778
- [x] EKS bootstrap provider - issue #1779
- [x] EKS support in clusterawsadm- issue #1780
- [x] EKS unmanaged node support - issue #1784
- [ ] EKS managed node group support - issue #1785
- [ ] EKS Fargate profiles support - issue #1786
- [x] Create template flavours to support EKS - issue #1828
- [x] Update documentation for AWSManagedCluster kubeconfigs - issue #1851 
- [ ] Support granting additional IAM roles access to the EKS cluster - issue #1850

**Comment by detiber** [comment]
@richardcase I haven't followed along with the Managed proposal linked overly well, but I would expect that it should be possible to implement a Managed kubernetes provider leveraging a Control Plane provider and a MachinePool provider targeted towards EKS. See https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/482 and the related discussion there.

**Comment by richardcase** [comment]
Thanks @detiber  - i was was just reading your comments on the PR in the Azure provider. I'll follow the approach you suggest.

Would you suggest that the managed control plan provider code be placed in `controlplane\eks` (or `controlplane\managed`)  in this repo?

**Comment by detiber** [comment]
@richardcase lets do `controlplane/eks` since it's more aligned with the implementation.

**Comment by richardcase** [comment]
@detiber - do you think the eks control plane should reuse the services ([for example](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/vpc.go#L41)) or should it have its own specific versions? If we re-use then we would have to use the cluster scope for example and that expects a AWSCluster, which we could create with the control plane controller. Either way i'm adding an eks service

**Comment by detiber** [comment]
@richardcase I think it would make sense to re-use where possible. We should probably consider refactoring common services (on an as needed basis) to remove the need for a scope to better accommodate the reuse

**Comment by richardcase** [comment]
@detiber - i've started to refactor the ec2 service so that networking side could be reused. Instead of removing the need for a scope i split out the networking into a _network service_  and associated _clusternetwork scope_......i misread the last part of your comment about removing the need for a scope completely. 

Shall i change what i've done to remove the new scope and change [ReconcileNetwork](https://github.com/richardcase/cluster-api-provider-aws/blob/service-refactor/pkg/cloud/services/ec2/network/network.go#L24) to accept a`NetworkParams` (or something similar) instead? It would only be a minor change.

**Comment by richardcase** [comment]
Work is progressing on this:

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: EksControlPlane
metadata:
  name: capi-managed-test-control-plane
  namespace: default
spec:
  roleArn: arn:aws:iam::12345678:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS
  version: v1.15
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-managed-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: EksControlPlane
    name: capi-managed-test-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: capi-managed-test
```

 A couple of questions:

1. A reference to a infrastructure cluster is required. Should i create **AWSManagedCluster** or update **AWSCluster** to have a **IsManaged** property? 
2. Can the new controllers run under the existing manager or does it have to be a new 'control plane manager' under `controlplane/eks`? I've started with the later as it was agreed above and is similar to the kubeadm control plane and but it would be simpler to have it part of the existing manager with flags to enable.
3. If we stick with a separate eks control plane manager which reconciles `EksControlPlane` should it also reconcile any additional resources like `AWSManagedCluster` as well or would they be handled by the existing manager?

@detiber - would be good to get your thoughts on the above.
