### ISSUE TITLE
AWSCluster v1alpha3 converts sourceSecurityGroupIds to null

### ISSUE THREAD

**Issue by rudoi** [kubernetes-sigs/cluster-api-provider-aws#1554]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I noticed after conversion in the status of my AWSCluster:
```yaml
ingressRule:
  - cidrBlocks:
    - 0.0.0.0/0
    description: Node Port Services
    fromPort: 30000
    protocol: tcp
    sourceSecurityGroupIds: null
    toPort: 32767
```

in the logs:
```
invalid: [status.network.securityGroups.node.ingressRule.sourceSecurityGroupIds: Invalid value: \"null\": status.network.securityGroups.node.ingressRule.sourceSecurityGroupIds in body must be of type array: \"null\",
```

**What did you expect to happen:**
`sourceSecurityGroupIds` should probably be `[]`, I think?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Do we have to add custom conversions to support this? How was this behavior the default?

**Environment:**

- Cluster-api-provider-aws version: master
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`): ubuntu 18.04
