### ISSUE TITLE
Document that AWSCluster spec.controlPlaneEndpoint is controller managed

### ISSUE THREAD

**Issue by moensch** [kubernetes-sigs/cluster-api-provider-aws#1719]
/kind bug

**What steps did you take and what happened:**
We have a need to create ALIAS records for the control plane endpoint and hence need that hostname to be part of the dnsAltNames in the control plane certificate.

I noticed that when I set `spec.controlPlaneEndpoint` in the `AWSCluster` the right thing happens for the cert - this endpoint name is included in the altNames as expected.

However, the awscluster controller is hard wired to **always** try to update that field in the spec:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/v0.5.3/controllers/awscluster_controller.go#L179-L182

This is causing a continuous reconcile failure in the `AWSCluster` (but everything else works, machines are created, control plane is up, etc...):
```
E0511 05:08:15.727788       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="admission webhook \"validation.awscluster.infrastructure.cluster.x-k8s.io\" denied the request: AWSCluster.infrastructure.cluster.x-k8s.io \"mycluster\" is invalid: spec.controlPlaneEndpoint: Invalid value: internal-mycluster-apiserver-XXX.us-east-1.elb.amazonaws.com:6443: field is immutable"  "controller"="awscluster" "request"={"Namespace":"aws-XXX","Name":"mycluster"}
```

**What did you expect to happen:**
The awscluster controller should only set `spec.controlPlaneEndpoint` if it is nil.

**Anything else you would like to add:**
Since the original issue I'm trying to solve is around dns names - is there a different way of adding extra dnsNames to the control plane certificate?

**Environment:**

- Cluster-api-provider-aws version: v0.5.3
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): `Ubuntu 18.04.4 LTS` (default CAPA AMI)

**Comment by randomvariable** [comment]
Thanks for the Slack reminder @moensch , oops.

Two things here:
You can potentially add the aliased record to the certificate SANs with something like:

```yaml
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "test"
spec:
...
  kubeadmConfigSpec:
...
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
		certSANs:
        - my-alias.company.internal
```

This wouldn't require any changes to Cluster API, but would add the alias to the SANs on the certificate.
