### ISSUE TITLE
Creating a bastion with the `eks` flavor fails

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#1956]
/kind bug

**What steps did you take and what happened:**
Create a kind cluster, init the aws and eks-bootstrap providers. Render the `eks` flavour (i.e. cluster-template-eks.yaml) and then add fields to enable the bastion. For example the **AWSManagedControlPlane** definition should look like this:

```yaml
kind: AWSManagedControlPlane
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
metadata:
  name: "capi-managed-test-control-plane"
spec:
  region: "eu-west-2"
  sshKeyName: "capi-management-2"
  version: "v1.17.0"
  bastion:
    enabled: true
```

When this is applied reconciliation of the **AWSManagedControlPlane** fails with the following error:

```bash
[manager] E0919 04:35:36.278342       8 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile bastion host for AWSManagedControlPlane default/capi-managed-test-control-plane: failed to run instance: MissingParameter: When specifying a security group you must specify a group id for each item\n\tstatus code: 400, request id: a22fa765-cdaf-4de6-9993-8ae99b0565d4" "controller"="awsmanagedcontrolplane" "name"="capi-managed-test-control-plane" "namespace"="default"
```

**What did you expect to happen:**
A would expect the reconciliation to be successful and the bastion instance to be created.

**Anything else you would like to add:**
Found as part of investigating #1954 

**Environment:**

- Cluster-api-provider-aws version: 0.6.0
- Kubernetes version: (use `kubectl version`): 1.17
