### ISSUE TITLE
AMI build/test/publish automation

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#1982]
Based on the feedbacks in https://docs.google.com/document/d/142YzzRj2H_OWEUE03Vrw3D-XpDCWM8RviFGHT5-RBxo/edit?usp=sharing:

An AMI-version.yaml will be added to the CAPA repository that contains all Kubernetes releases that CAPA AMIs are created from. 
 `AMI-version.yaml` can be similar to: 
```
BUILDS:
  - '1.18.8':
      GO_VERSION: 1.13.5
      K8S_RELEASE:1.18.8
      IMAGE_BUILDER_VERSION: 0.1.6
      BUILD_REVISION: 0
      ARCHITECTURE: x86-64
      EXTRA_CONFIG_FILE: 'extra-configs.yaml'
      OS:
       - centos-7
       - ubuntu-1804
  - '1.19.1':
      CONFIG: '1.16'
      GO_VERSION: 1.13.5
      K8S_RELEASE:1.19.1
```

Aso, a `CAPA-robot` similar to k8s-release-robot will be created to automatically create PRs when there are new Kubernetes releases.

Roughly, we will need 4 different Prow jobs to automate build/test/publish workflow:

**Periodic Kubernetes release detection job**: will periodically checks if there is a new Kubernetes release and  if there is a new release, it creates a `new-release PR` using CAPA-bot to CAPA repository by adding the new release to the `AMI-version.yaml`.

**Pre-submit test-AMI build job**: This job will get triggered when there is a PR that modifies `AMI-version.yaml` like `new-release PR`. It builds AMIs following the changes in the `AMI-version.yaml`. These AMIs will be used to run conformance tests. Here, we need to have a way to detect changes in the `AMI-version.yaml` and only act on them. api-machinery is one option. This job will use CNCF AWS account.

**Pre-submit AMI conformance test job**: will detect the changes in `AMI-version.yaml` and run conformance tests using only the AMIs that are recently built. This job will use test AWS account.

**Post-submit AMI promote job**: After manually merging the PR created by the `CAPA-robot` (after observing conformance tests pass), new “published” AMIs will be created referencing the same EBS snapshot used by test AMIs, which acts as “promotion” of the image. This job will use CNCF AWS account.

**Pre-submit clean-up job**: This can be a job that will be triggered manually to delete all the newly created AMIs after a PR is created. This may become handy if conformance tests fails and we will need to retrigger `Pre-submit test-AMI build job`.

To initiate a rebuild for either fixing a previous AMI image or including some OS patches; instead of the periodic job, a PR will be manually created with a new BUILD_REVISION. The rest of the workflow is same with creating a new AMI.

Follow up issue to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1861
