### ISSUE TITLE
AWSMachineTemplate defaulting and validation for `spec.cloudInit.insecureSkipSecretsManager` are in conflict

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2064]
/kind bug

**What steps did you take and what happened:**

The AWSMachineTemplate defaulting webhook [sets `spec.cloudInit.secureSecretsBackend` to `secrets-manager`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/16515f764e272018be1cf0a56c2ea7c64468a508/api/v1alpha3/awsmachine_webhook.go#L179) if it is not specified, even when  `spec.cloudInit.insecureSkipSecretsManager` is set to `true`.

This seems to conflict with the validating webhook, which [forbids this combination](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/16515f764e272018be1cf0a56c2ea7c64468a508/api/v1alpha3/awsmachine_webhook.go#L124).

FWIW, the AWSMachineController _requires_ that [`spec.cloudInit.secureSecretsBackend` be set either to `secrets-manager`, or `ssm-parameter-store`](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/16515f764e272018be1cf0a56c2ea7c64468a508/controllers/awsmachine_controller.go#L101). If some value is required, then I my guess is that the validating rule linked to above should be removed.

I discovered this by creating this AWSMachineTemplate:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: dlipovetsky-test
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: dlipovetsky
      cloudInit:
        insecureSkipSecretsManager: true
```

And finding that the defaulting webhook had modified it to:
```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: dlipovetsky-test
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.large
      sshKeyName: dlipovetsky
      cloudInit:
        insecureSkipSecretsManager: true
        secureSecretsBackend: secrets-manager
```

**What did you expect to happen:**

**Environment:**

CAPA v0.6.1
