### ISSUE TITLE
CAPA pod crashLoopBackoff,  missing type registration

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/cluster-api-provider-aws#2078]
/kind bug

**What steps did you take and what happened:**
Initialize cluster api and apply YAML below:
```yaml
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "undistro-quickstart"
  namespace: "default"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: "undistro-quickstart"
    namespace: "default"
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "undistro-quickstart-control-plane"
    namespace: "default"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: "undistro-quickstart"
  namespace: "default"
spec:
  region: 'us-east-1'
  sshKeyName: "undistro"
  bastion:
    enabled: true
    disableIngressRules: true
---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "undistro-quickstart-control-plane"
  namespace: "default"
spec:
  replicas: 3
  infrastructureTemplate:
    kind: AWSMachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-control-plane"
    namespace: "default"
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: aws
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: aws
  version: "v1.19.1"
---
kind: AWSMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
metadata:
  name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-control-plane"
  namespace: "default"
spec:
  template:
    spec:
      instanceType: "t3.medium"
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: "undistro"
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: "undistro-quickstart-md-0"
  namespace: "default"
spec:
  clusterName: "undistro-quickstart"
  replicas: 3
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "undistro-quickstart"
      version: "v1.19.1"
      
      bootstrap:
        configRef:
          name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-md-0"
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          namespace: "default"
      infrastructureRef:
        name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-md-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        namespace: "default"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-md-0"
  namespace: "default"
spec:
  template:
    spec:
      instanceType: "t3.medium"
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: "undistro"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: "undistro-quickstart-b26f9301-0c82-43bd-9731-866fdc3295f9-md-0"
  namespace: "default"
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
          kubeletExtraArgs:
            cloud-provider: aws
```

**What did you expect to happen:**

create an aws self hosted cluster

**Anything else you would like to add:**

The EKS environment variable feature flags are setted in my environment during initialization of CAPA, but in this case I just initialize infrastructure because I do not need for this cluster creation 

Pod Log

```
E1028 16:16:21.077425       1 main.go:255] setup "msg"="problem running manager" "error"="no matches for kind \"AWSManagedControlPlane\" in version \"controlplane.cluster.x-k8s.io/v1alpha3\"" 
```

**Environment:**

- Cluster-api-provider-aws version: 0.6.1
- Kubernetes version:` Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"} `
- OS `NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`
