### ISSUE TITLE
Consider renaming spec.networkSpec to spec.network

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-aws#2119]
/kind feature

**Describe the solution you'd like**
The field called `networkSpec` seems redundant given that's already under `spec`, we can simplify by calling it just `network`.

**Comment by Ankitasw** [comment]
@sedefsavas / @vincepri Shall we rename networkSpec as `network` or `spec`, got confused with the issue title and description

**Comment by Ankitasw** [comment]
After renaming, the API change should look like below ( for e.g )
```
spec:
  network:
    vpc:
      cidrBlock: 10.50.0.0/16
    subnets:
    - availabilityZone: us-west-2a
      cidrBlock: 10.50.0.0/20
      isPublic: true
```
Is my understanding correct?
