### ISSUE TITLE
When using unmanaged VPCs, security group rules are deleted

### ISSUE THREAD

**Issue by jyyeom** [kubernetes-sigs/cluster-api-provider-aws#2143]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Deploy with an AWSCluster with unmanaged VPCs and Subnets with v0.6.3.
During provisioning, the inbound rules of three SGs(bastion, apiserver-lb, lb) are created and deleted repeatedly and after minutes, just SGs without rules remain.
But the inbound rules of SGs(controlplane, nodes) are kept as expected.

**What did you expect to happen:**
the inbound rules of SGs(bastion, apiserver-lb, lb) are not deleted.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

<details>
<summary>config.yaml</summary>

```
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-test-01
  namespace: capi-test-01
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-test-01-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: capi-test-01

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: capi-test-01
  namespace: capi-test-01
spec:
  networkSpec:
    vpc:
      id: vpc-xxxx
    subnets:
    - id: subnet-yyyy # private-2a
      isPublic: false
    - id: subnet-yyyy # private-2b
      isPublic: false
    - id: subnet-yyyy # private-2c
      isPublic: false
    - id: subnet-yyyy # public-2a
      isPublic: true
    - id: subnet-yyyy # public-2b
      isPublic: true
    - id: subnet-yyyy # public-2c
      isPublic: true
  region: ap-northeast-2
  sshKeyName: test-key
  controlPlaneLoadBalancer:
    scheme: "internal"
    crossZoneLoadBalancing: false
    subnets:
    - subnet-zzzz
    - subnet-zzzz
    - subnet-zzzz
  bastion:
    enabled: true
    allowedCIDRBlocks:
    - "0.0.0.0/0"
    instanceType: t3.small
    ami: ami-087d9d146bcc706f9

# controlplane
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capi-test-01-control-plane
  namespace: capi-test-01
spec:
  replicas: 3
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSMachineTemplate
    name: capi-test-01-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: aws
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname }}'
        kubeletExtraArgs:
          cloud-provider: aws
  version: v1.18.12

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-test-01-control-plane
  namespace: capi-test-01
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.xlarge
      ami:
        id: ami-087d9d146bcc706f9
      sshKeyName: aws-x02-01
      additionalTags:
        instanceType: "control-plane"
        instanceGroup: "control"
      additionalSecurityGroups:
      - id: sg-abc



# Worker Nodes
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: capi-test-01-md-0
  namespace: capi-test-01
spec:
  clusterName: capi-test-01
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      clusterName: capi-test-01
      version: v1.18.12
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: capi-test-01-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: capi-test-01-md-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-test-01-md-0
  namespace: capi-test-01
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.xlarge
      ami:
        id: ami-087d9d146bcc706f9
      sshKeyName: test-key
      additionalTags:
        instanceType: "worker-node"
        instanceGroup: "woker-group-1"
      additionalSecurityGroups:
      - id: sg-abc
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capi-test-01-md-0
  namespace: capi-test-01
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'
```

</details>

**Environment:**

- Cluster-api-provider-aws version: v0.6.3
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
