### ISSUE TITLE
Comparison to Internet-facing with controlPlaneLoadBalancer scheme is too unforgiving

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-aws#2155]
/kind bug

**What steps did you take and what happened:**
Create a new cluster with the following:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
...
spec:
  controlPlaneLoadBalancer:
    scheme: internet-facing
...
```

The API Server's Load Balancers will come up in the *private subnets* and be unable to receive any incoming traffic from the internet.  The Load Balancer is still properly created with an internet-facing scheme in AWS.

**What did you expect to happen:**

Some form of case insensitive comparison should occur or an error message that `internet-facing` is an invalid entry should happen.  Also, the Load Balancer should come up in the *public subnets* not the private ones.

**Anything else you would like to add:**

Thank you to @randomvariable and @scottslowe for assistance in troubleshooting this very peculiar bug.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
