### ISSUE TITLE
Set ASG subnet to only private subnets

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2191]
In AWSMachinePool, if subnets are not specified, we add all available subnets to the AutoScalingGroup.
Instead, the default should be only private subnets IMO. 

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/da8c0c4539a2aaaf64f570d95da7596d2bc683d0/pkg/cloud/services/autoscaling/autoscalinggroup.go#L148-L152
What do you all think?

**Comment by paurosello** [comment]
Hello @sedefsavas I think this feature is pretty much required in most scenarios. 

I cannot think of a case were we want to have machines in public subnets.

I tried using filters for subnets in the MachinePool to overcome this issue but as pointed out in the code on the initial comment, only the ID is used, filters are ignored. This is how it would look like with a filter:

```
   subnets:
     - filters:
       - name: sigs.k8s.io/cluster-api-provider-aws/role
         values:
           - private
```
