### ISSUE TITLE
EkS kubelet-extra-args are not set when using machinepool

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/cluster-api-provider-aws#2224]
/kind bug

**What steps did you take and what happened:**

```yaml
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: undistro-quickstart-mp-0
  namespace: default
spec:
  clusterName: undistro-quickstart
  minReadySeconds: 0
  replicas: 1
  template:
    metadata: {}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: EKSConfigTemplate
          name: undistro-quickstart-mp-033dcec9-adbf-4e6d-b493-6db22e2d0e30-0
          namespace: default
      clusterName: undistro-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSManagedMachinePool
        name: undistro-quickstart-mp-0
        namespace: default
      version: v1.18.9
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedMachinePool
metadata:
  name: undistro-quickstart-mp-0
  namespace: default
spec:
  additionalTags:
    infra-node: "true"
  amiType: AL2_x86_64
  eksNodegroupName: undistro-quickstart-mp-0
  instanceType: t3.medium
  roleName: nodes.cluster-api-provider-aws.sigs.k8s.io
  scaling:
    maxSize: 5
    minSize: 1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: EKSConfigTemplate
metadata:
  name: undistro-quickstart-mp-033dcec9-adbf-4e6d-b493-6db22e2d0e30-0
  namespace: default
spec:
  template:
    spec:
      kubeletExtraArgs:
        node-labels: node-role.undistro.io/infra=true
        register-with-taints: dedicated=infra:NoSchedule
```

is generating wrong userdata

```
/etc/eks/bootstrap.sh default_undistro-quickstart --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-0dd0589ee7a07c236,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=undistro-quickstart-mp-0' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP


```

**What did you expect to happen:**

```
/etc/eks/bootstrap.sh default_undistro-quickstart --kubelet-extra-args '--node-labels=node-role.undistro.io/infra=true,eks.amazonaws.com/nodegroup-image=ami-0dd0589ee7a07c236,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=undistro-quickstart-mp-0 --register-with-taints=dedicated=infra:NoSchedule' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP
```

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v0.6.4
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
