### ISSUE TITLE
AWSMachineTemplate spec configurable EBS Volume throughput for gp3 type

### ISSUE THREAD

**Issue by wmgroot** [kubernetes-sigs/cluster-api-provider-aws#2254]
/kind feature

**Describe the solution you'd like**
The new gp3 type EBS volumes support configurable throughput, rather than calculating it from the size of the volume. Currently, there does not appear to be a way to set this parameter on the AWSMachineTemplate CRD.

> General Purpose SSD (gp3) volumes offer cost-effective storage that is ideal for a broad range of workloads. These volumes deliver a consistent baseline rate of 3,000 IOPS and 125 MiB/s, included with the price of storage. You can provision additional IOPS (up to 16,000) and throughput (up to 1,000 MiB/s) for an additional cost. 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html

AWSMachineTemplate root volume config.
```
rootVolume:
  description: RootVolume encapsulates the configuration options
    for the root volume
  properties:
    deviceName:
      description: Device name
      type: string
    encrypted:
      description: Encrypted is whether the volume should be
        encrypted or not.
      type: boolean
    encryptionKey:
      description: EncryptionKey is the KMS key to use to encrypt
        the volume. Can be either a KMS key ID or ARN. If Encrypted
        is set and this is omitted, the default AWS key will
        be used. The key must already exist and be accessible
        by the controller.
      type: string
    iops:
      description: IOPS is the number of IOPS requested for
        the disk. Not applicable to all types.
      format: int64
      type: integer
    size:
      description: Size specifies size (in Gi) of the storage
        device. Must be greater than the image snapshot size
        or 8 (whichever is greater).
      format: int64
      minimum: 8
      type: integer
    type:
      description: Type is the type of the volume (e.g. gp2,
        io1, etc...).
      type: string
```

**Environment:**

- Cluster-api-provider-aws version: 
```
clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.14", GitCommit:"5a09f69fa8c4892eb45a61d8d701140eeeaa5ba8", GitTreeState:"clean", BuildDate:"2021-02-06T03:08:57Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}

clusterawsadmin version
clusterawsadm version: &version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.4", GitCommit:"634f30eb5a3ab42ec21e358cfb86da740784aed7", GitTreeState:"clean", BuildDate:"2021-01-22T14:42:00Z", GoVersion:"go1.13.15", AwsSdkVersion:"v1.36.26", Compiler:"gc", Platform:"darwin/amd64"}
```
