### ISSUE TITLE
Subnet filtering does not allow for multi-az usage

### ISSUE THREAD

**Issue by rsmitty** [kubernetes-sigs/cluster-api-provider-aws#2298]
/kind bug

**What steps did you take and what happened:**
I encountered this during a larger bit of research into how to achieve multi-az/subnet usage with the CAPA provider. Note that I'm attempting to use pre-created VPC and subnet info instead of the provider doing this for me.

When using something like subnet filters in an AWSMachineTemplate, only a single subnet with the tags was returned. An example of the tag-key filtering used:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: wut-controlplane
  namespace: default
spec:
  template:
    spec:
...
...
      subnet:
        filters:
          - name: tag-key
            values:
              - for-capi
```

**What did you expect to happen:**
I've been scratching my brain trying to figure out a good way to make multi-az happen with this provider. My expectation was that when using filters in the method above for subnets in us-east-1[a,b,c], the selected subnet would be randomized and result in the ability to do a naive implementation of multi-az.

**Anything else you would like to add:**
The subnets are filtered and returned [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/instances.go#L316), which shows that subnet[0] is always returned, thus rendering the filtering kind of useless for any number of subnets tagged greater than 1.

Some further info from the slack thread about this: https://kubernetes.slack.com/archives/CD6U2V71N/p1615500253028000

**Environment:**

- Cluster-api-provider-aws version: 0.6.4
- Kubernetes version: (use `kubectl version`): 1.20.4
- OS (e.g. from `/etc/os-release`): Talos v0.9.x
