### ISSUE TITLE
Machine pool controller does try to create a new Auto Scaling Group if it failed to do so previously due to misconfiguration that passes validation

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-aws#2332]
/kind bug

**What steps did you take and what happened:**

1. Create an AWS cluster.
2. Create a MachinePool with desired capacity (`spec.replicas`) of 10.
3. Create an AWSMachinePool with a max size of (`spec.maxSize`) of 5.

```yaml
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: test-pool-0
spec:
  clusterName: test-cluster
  replicas: 10
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfig
          name: test-pool-0
      clusterName: single-node-pool
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachinePool
        name: test-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachinePool
metadata:
  name: "wkp-mgmt01-pool-0"
spec:
  scaling:
    minSize: 1
    maxSize: 5
```

Because the desired capacity is greater than the maxSize,  the AWSMachinePool controller fails to create an Auto Scaling Group:

```shell
Events:
  Type     Reason                         Age   From                       Message
  ----     ------                         ----  ----                       -------
  Normal   FailedDescribeInstances        27m   aws-controller             No Auto Scaling Groups with test-pool-0 found
  Warning  FailedLaunchTemplateReconcile  7m14s (x13 over 26m)  awsmachinepool-controller  (combined from similar events): Failed to reconcile launch template: ValidationError: AutoScalingGroup name not found - AutoScalingGroup test-pool-0 not found
           status code: 400, request id: 97b882e6-be73-4727-b401-485fb5893286
```

I then updated the AWSMachinePool maxSize to 10, but nothing changed; I think that's because the AWSMachinePool controller found no Auto Scaling Group to update, and it did not try to create a new one.

**What did you expect to happen:**
When the maxSize (and perhaps another field?) changes, but no Auto Scaling Group is found, I expect the AWSMachinePool controller to try to create a new Auto Scaling Group.

**Anything else you would like to add:**
Together, a valid MachinePool, and a valid AWSMachinePool, can prevent the AWSMachinePool controller from creating an Auto Scaling Group. That's unfortunate. But I suppose it makes sense, if one views AWSMachinePool as the _constraints_ on MachinePool.

**Environment:**

- Cluster-api-provider-aws version: v0.6.4
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):
