### ISSUE TITLE
New 0.6.5 EKS cluster with new awsclustercontrolleridentities is having issues with capa-eks-control-plane-controller-manager

### ISSUE THREAD

**Issue by martin-ducar-gd** [kubernetes-sigs/cluster-api-provider-aws#2358]
/kind bug

**What steps did you take and what happened:**
```sh
clusterctl init -i aws -c kubeadm:v0.3.14,aws-eks -b kubeadm:v0.3.14,aws-eks --core cluster-api:v0.3.14
```

than deploy cluster with setup:
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSClusterControllerIdentity
metadata:
  name: "default"
spec:
  allowedNamespaces: {} 
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "mgmt01"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSManagedCluster
    name: "mgmt01"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "mgmt01-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedCluster
metadata:
  name: "mgmt01"
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "mgmt01-control-plane"
spec:
  region: "us-east-1"
  sshKeyName: "capi-management"
  version: "v1.19.8"
  identityRef:
    kind: AWSClusterControllerIdentity
    name: default
```

in log of capa-eks-control-plane-controller-manager
```sh
$ kubectl logs -c manager -n capa-eks-control-plane-system       capa-eks-control-plane-controller-manager-<hash>
...
E0419 12:35:48.487128       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.9/tools/cache/reflector.go:105: Failed to list *v1alpha3.AWSClusterControllerIdentity: awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:capa-eks-control-plane-system:capa-eks-control-plane-controller-manager" cannot list resource "awsclustercontrolleridentities" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
...
```
**What did you expect to happen:**
Cluster to spin up

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.6.5
- Kubernetes version: (use `kubectl version`): 1.20.2
- OS (e.g. from `/etc/os-release`): 
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
```
