### ISSUE TITLE
component Deployment affinity not set

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-aws#2361]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Download https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v0.6.5/infrastructure-components.yaml

Both deployments have:
```
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
```

But there is no affinity or node-selector to run on the control-plane.

Following the [quickstart](https://cluster-api.sigs.k8s.io/user/quick-start.html?highlight=iam#initialize-the-management-cluster) there will be 2 IAM polices, 1 that is used by the workers and 1 by the control-plane.

When running `clusterctl move` the controllers could land on worker nodes.

**What did you expect to happen:**
The controller (and webhook?) should run on the control-plane nodes with elevated permissions.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
   https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v0.6.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
I agree we should probably do this.

**Comment by vespian** [comment]
PTAL: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2377

**Comment by sedefsavas** [comment]
I think we should backport this, as this can be considered as bugs.
/kind backport

**Comment by dlipovetsky** [comment]
We're using the control plane node label as a _proxy_ for "this node has the IAM instance profile the CAPA controller needs."

When CAPA uses bootstrap credentials, it can run on any node.
When CAPA runs in EKS, the IAM instance profile is added to non-control-plane nodes.

In these two cases, required affinity to control plane nodes is not necessary, and in the EKS case, the lack of control plane nodes  prevents CAPA from running.

**Comment by dkoshkin** [comment]
>But regardless of what label we use, I think we'll want to use required anti-affinity.

@dlipovetsky I was following until the anti-affinity part, why use anti-affinity instead of an affinity with some new labels?

**Comment by dlipovetsky** [comment]
> why use anti-affinity instead of an affinity with some new labels?

My mistake. I forgot that there is no concept of _node_ anti-affinity :disappointed: 

> inter-pod affinity/anti-affinity constrains against pod labels rather than node labels
> -- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

**Comment by richardcase** [comment]
@dlipovetsky @dkoshkin  - i like the idea of using node labels and affinity. From the EKS side this would work as we can create a node group with labels if we want to segregate CAPA.

We could also consider taints/tolerations (we have #2399 to add taint support to managed machine pools)

**Comment by sedefsavas** [comment]
+1 to labels and affinity.
Also,  @dkoshkin if we want to backport this, it should also be backward compatible. But if it will make it too complicated, I am fine with just adding this to v0.7.0 too.

**Comment by sedefsavas** [comment]
Let's discuss this on May 31st meeting, I added it to the agenda.
cc @dkoshkin

**Comment by richardcase** [comment]
We're probably going to have to use a combination of `tolerations` and `nodeAffinity` with the managers to get this working for EC2/KCP and EKS based clusters. Tested this with EKS and it schedules ok:

```yaml
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
```

We should probably introduce a env var in the definitions to specify the controlplane node label name and default it to `node-role.kubernetes.io/master` so that for EKS clusters we can optionally override this if we have nodes that are used for "system" services. So we'd end up with something like this:

```yaml
  tolerations:
    - effect: NoSchedule
      key: ${K8S_MASTER_LABEL:=node-role.kubernetes.io/master}
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: ${K8S_MASTER_LABEL:=node-role.kubernetes.io/master} 
            operator: Exists
```

I could do this as part of #2570 as i will making changes to the managers yaml anyway.
