### ISSUE TITLE
eks controller requires namespace access to support StaticIdentity defined in other namespaces

### ISSUE THREAD

**Issue by paulcarlton-ww** [kubernetes-sigs/cluster-api-provider-aws#2372]
/kind bug

**What steps did you take and what happened:**
I configured an AWS Cluster using StaticIdentity provider.

```yaml
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: "mgmt01"
  namespace: "cx"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSManagedCluster
    name: "mgmt01"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "mgmt01-control-plane"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedCluster
metadata:
  name: "mgmt01"
  namespace: "cx"
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
metadata:
  name: "mgmt01-control-plane"
  namespace: "cx"
spec:
  region: "eu-west-1"
  sshKeyName: "capi-management"
  version: "v1.18.0"
  addons:
    - name: "vpc-cni"
      version: "v1.6.3-eksbuild.1"
      conflictResolution: "overwrite"
  identityRef:
    kind: AWSClusterStaticIdentity
    name: cx-account
---
apiVersion: exp.cluster.x-k8s.io/v1alpha3
kind: MachinePool
metadata:
  name: "mgmt01-pool-0"
  namespace: "cx"
spec:
  clusterName: "mgmt01"
  replicas: 2
  template:
    spec:
      clusterName: "mgmt01"
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        name: "mgmt01-pool-0"
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSManagedMachinePool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedMachinePool
metadata:
  name: "mgmt01-pool-0"
  namespace: "cx"
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/ns: "cxlabel"
  name: "cx"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSClusterStaticIdentity
metadata:
  name: "cx-account"
spec:
  secretRef:
    name: cx-account-creds
    namespace: cx
  allowedNamespaces:
    selector:
      matchLabels:
        cluster.x-k8s.io/ns: "cxlabel"
```

**What did you expect to happen:**
The controller to process my cluster definition. However it failed with rbac error listing namespaces.
Fixed this by adding namespaces to clusterrole used by controller

**Anything else you would like to add:**
Note that I also had to add `cluster.x-k8s.io/ns: "cxlabel"` label to the `control-plane-aws-eks` namespace

**Environment:**

- Cluster-api-provider-aws version:  v0.6.5
- Kubernetes version: (use `kubectl version`): v1.20.2 (Kind)
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04
