### ISSUE TITLE
extraStatements in the clusterAPIControllers config for clusterawsadm is being ignored

### ISSUE THREAD

**Issue by vtremblay** [kubernetes-sigs/cluster-api-provider-aws#2387]
/kind bug

**What steps did you take and what happened:**
When using `clusterawsadm` to create IAM roles, we cannot add inline statements for the controllers. The field from the configuration is accepted but ignored.

Here is the configuration used to reproduce:

```
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
kind: AWSIAMConfiguration
spec:
  eks:
    enable: true
    allowIAMRoleCreation: true 
    defaultControlPlaneRole:
      disable: true
    managedMachinePool:
      disable: false
  clusterAPIControllers:
    disabled: false
    extraStatements:
      - Action:
          - "iam:GetPolicy"
        Effect: "Allow"
        Resource:
          - "*"
```

The `clusterawsadm` command is working and does not fail, but the inline policy is not created.

**What did you expect to happen:**
I expected an inline policy to be added to the controllers role. But nothing happened.

**Environment:**

- Cluster-api-provider-aws version: 0.6.5
- Kubernetes version: (use `kubectl version`): v1.16.15-eks-ad4801
- OS (e.g. from `/etc/os-release`):
