### ISSUE TITLE
Cannot create managed machine pools with ssh key set

### ISSUE THREAD

**Issue by wmedlar** [kubernetes-sigs/cluster-api-provider-aws#2389]
/kind bug

**What steps did you take and what happened:**
1. Create a cluster manifest with the `eks-managedmachinepool` flavor:

    ```shell
    $ clusterctl config cluster my-cluster --flavor eks-managedmachinepool --kubernetes-version v1.18.18 > cluster.yaml
    ```

1. Edit the AWSManagedMachinePool `spec.remoteAccess.sshKeyName` to match the ssh key in the AWSManagedControlPlane. 

    ```yaml
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: AWSManagedControlPlane
    metadata:
      name: my-cluster-control-plane
    spec:
      bastion:
        enabled: true
      region: us-east-1
      sshKeyName: my-ssh-keypair
      version: v1.18.18
    ---
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSManagedMachinePool
    metadata:
      name: my-cluster-nodegroup-01
    spec:
      remoteAccess:
        sshKeyName: my-ssh-keypair
    ---
    [...]
    ```

1. Apply the cluster manifest.
1. The AWSManagedMachinePool will immediately fail reconciliation with `EKSNodegroupReconciliationFailed`.

    ```shell
    $ kubectl describe awsmanagedmachinepool my-cluster-nodegroup-01
    [...]
    Status:
      Conditions:
        Last Transition Time:  2021-05-06T21:43:34Z
        Message:               1 of 2 completed
        Reason:                EKSNodegroupReconciliationFailed
        Severity:              Error
        Status:                False
        Type:                  Ready
        Last Transition Time:  2021-05-06T21:57:52Z
        Message:               failed to create nodegroup: failed to create nodegroup: InvalidRequestException: You are not authorized to perform ec2:DescribeKeyPairs.
    {
      RespMetadata: {
        StatusCode: 400,
        RequestID: "75c81e3e-005c-4015-9bb1-b55147edcb0b"
      },
      ClusterName: "capa-poc_my-cluster-control-plane",
      Message_: "You are not authorized to perform ec2:DescribeKeyPairs.",
      NodegroupName: "capa-poc_my-cluster-nodegroup-01"
    }
        Reason:                EKSNodegroupReconciliationFailed
        Severity:              Error
        Status:                False
        Type:                  EKSNodegroupReady
        Last Transition Time:  2021-05-06T21:43:32Z
        Status:                True
        Type:                  IAMNodegroupRolesReady
      Ready:                   false
    ```

**What did you expect to happen:**

Managed machine pool is able to create instances with the specified ssh keypair.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

- IAM roles were created with clusterawsadm v0.6.5 and the following config:

    ```yaml
    apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
    kind: AWSIAMConfiguration
    spec:
      clusterAPIControllers:
        disable: false

      bootstrapUser:
        enable: false
      controlPlane:
        disable: true
      nodes:
        disable: true

      eks:
        enable: true
        iamRoleCreation: false
        defaultControlPlaneRole:
          disable: false
        fargate:
          disable: false
        managedMachinePool:
          disable: false
    ```

- CAPA & EKS control plane are running with the `arn:aws:iam::my-account-id:role/controllers.cluster-api-provider-aws.sigs.k8s.io` attached
- AWSManagedMachinePool is using default role `arn:aws:iam::my-account-id:role/controllers.cluster-api-provider-aws.sigs.k8s.io`

**Environment:**

- Cluster-api-provider-aws version: v0.6.5
- Kubernetes version: (use `kubectl version`):
  - management cluster: v1.18.18
  - workload cluster: v1.18.18
- OS (e.g. from `/etc/os-release`): linux

**Comment by wmedlar** [comment]
My workaround for this is binding `arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess` (this is the smallest managed policy I could find with `ec2:DescribeKeyPairs`) to the CAPA & EKS controller role.

```yaml
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
kind: AWSIAMConfiguration
spec:
  clusterAPIControllers:
    extraPolicyAttachments:
    - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
```
