### ISSUE TITLE
Add IPv6 support

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2420]
Add support to create IPv6 clusters and add e2e test for it.

/kind feature
/milestone next

**Comment by sedefsavas** [comment]
Reminder:
Create issue for dual-stack
and replicate this for EKS

**Comment by richardcase** [comment]
This gets messy with EKS.

**Comment by randomvariable** [comment]
Support should be fixed in Cluster API, not by shoving lots of non-standard behaviour into CAPA - consistency across providers is paramount. We need to break this down. Please start a doc, we have a team at VMware looking into dual-stack in general who can assist.

**Comment by richardcase** [comment]
@randomvariable  - started a [doc](https://docs.google.com/document/d/1-J3whrf2ewOJ22G3ETZYOAh6zysTf37ecCtttmggzlM/edit?usp=sharing)

**Comment by randomvariable** [comment]
/assign

for initial scoping

**Comment by yandooo** [comment]
Are there any updates here?

**Comment by yandooo** [comment]
@richardcase would it be possible to share relevant documentation for the topic if any? As per [comment](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2420#issuecomment-959022716)  there seems like some progress is made towards standardizing CAPI to support dual-stack. Thanks

**Comment by richardcase** [comment]
There isn't a huge amount of documentation. The doc mentioned in the thread was the start of a doc to capture notes but we didn't much further. Do you have access to that doc?

**Comment by yandooo** [comment]
@richardcase don't have it. I requested access linking your comment in the request message. Appreciated it if it can be shared. Thanks

**Comment by richardcase** [comment]
> @richardcase don't have it. I requested access linking your comment in the request message. Appreciated it if it can be shared. Thanks

Just sent you an email @yandooo :smile:

**Comment by yandooo** [comment]
I tend to agree on getting IPv6 out first and look at dual stack cohesively to unlock AWS EKS ipv6 feature @sedefsavas.

**Comment by richardcase** [comment]
I also think that adding IPv6 first is a good way forward.

**Comment by richardcase** [comment]
@Skarlso - this was the issue i was thinking og.

**Comment by Skarlso** [comment]
Hi! :) 

Let's tackle this! :) We have some experience creating the necessary resources in eksctl, so hopefully, I can be of assistance here.

**Comment by nikimanoledaki** [comment]
I would love to collaborate on this too! I worked on planning IPv6 for eksctl and implementing it alongside @Skarlso. :) See: https://github.com/weaveworks/eksctl/issues/4255

**Comment by richardcase** [comment]
Awesome, thanks :+1: 

/assign nikimanoledaki

**Comment by sedefsavas** [comment]
I came across this old PR for IPv6 support: 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1322 https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1370

Might be useful.

**Comment by sedefsavas** [comment]
Also CAPZ IPv6 support implementation: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/646

**Comment by yandooo** [comment]
Does the following CR creation experience look acceptable?

AWS provided CIDR:

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-001-cluster
  namespace: aws-account-458764
spec:
  # no need for pod CIDR block for AWS provided ipv6 CIDR
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-001-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-001-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: eks-001-control-plane
  namespace:  aws-account-458764
spec:
  eksClusterName: eks-inst-001
  region: us-east-1
  network:
      vpc:
           # Optiona: by default set to true?
           providedIpv6CidrBlock: true
```

Fine-graned configuration assuming CIDR block known upfront (from ipv6 pool):

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: eks-001-cluster
  namespace: aws-account-458764
spec:
    clusterNetwork:
    pods:
      cidrBlocks:
      - 2001:10:10:10::/56
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-001-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: eks-001-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: eks-001-control-plane
  namespace:  aws-account-458764
spec:
  eksClusterName: eks-inst-001
  region: us-east-1
  network:
      vpc:
           providedIpv6CidrBlock: false
          # optional
           ipv6CidrBlock: 2001:10:10:10::/56
           subnets:
                - id: sn-001
                  availabilityZone: us-east-1a
		 cidrBlock:        10.1.0.0/16
                  # Optional
		 ipv6CidrBlock:  2001:10:10:a::/64
                  # Optional. Enabled ipv6 allocation for the subnet
                  isIpv6: true
		 isPublic:         false
```
