### ISSUE TITLE
Permission error when enable EKS encryption

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2432]
/kind bug
/area provider/eks
/priority important-soon
/milestone v0.7.0

**What steps did you take and what happened:**
Create an EK cluster and enable encruption using a KMS key. For example:
```yaml
 encryptionConfig:
    provider: "arn:aws:kms:us-east-1:12345678:alias/aws/eks"
    resources:
    - "secrets"
```

You then receive the following error:
```
 Warning  FailedCreateEKSControlPlane                   2s    aws-controller  Failed to initiate creation of a new EKS control plane: InvalidRequestException: User not authori │
│ zed to perform kms:CreateGrant operatio
```

**What did you expect to happen:**

I expect the cluster to provision with an error or warning and the EKS encryption settings to be set. 

**Environment:**

- Cluster-api-provider-aws version: 0.6.6

**Comment by richardcase** [comment]
This will need to be backported to 0.6 as well

**Comment by martin-ducar-gd** [comment]
It seems issue really is with something different we used aws eks for KMS
```yaml
  encryptionConfig:
    provider: "arn:aws:kms:us-east-1:123456789012:alias/aws/eks"
    resources:
    - "secrets"
```
that key is not working at all as policy is bad on his side and kms:CreateGrant is not allowed once the custom KMS key with proper policy is there it will start working
