### ISSUE TITLE
Cannot SSH into eks nodegroup instances using bastion

### ISSUE THREAD

**Issue by abhinavnagaraj** [kubernetes-sigs/cluster-api-provider-aws#2442]
/kind bug

**What steps did you take and what happened:**
1) Create an EKS cluster with bastion enabled in public subnet and workers in private subnets.
2) Configure the SSH key in both AWSManagedControlPlane and AWSManagedMachinePool
3) After the cluster is ready, 
    i) first ssh into the bastion using the provided ssh key - this is successful
    ii) from the bastion, using the same ssh key, try to ssh into any of the worker nodes - this fails

The worker nodes have security groups "eks-cluster-sg-" and "eks-remoteAccess-".
The "eks-remoteAccess-" has a TCP 22 inbound rule from sg "-node-eks-additional", which in turn has the TCP 22 inbound rule for sg "-bastion".

Note: Adding a security group as a source does not add rules from the source security group.

Directly updating the worker node's inbound rules with the TCP 22 inbound rule from "-bastion" works -- this allows ssh from bastion to worker nodes.

```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-quickstart-control-plane
  namespace: default
spec:
  eksClusterName: capi-eks-quickstart
  region: us-east-1
  version: v1.19.0
  sshKeyName: <my-ssh-key>
  bastion:
    allowedCIDRBlocks:
    - 0.0.0.0/0
    enabled: true
```

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSManagedMachinePool
metadata:
  name: capi-eks-quickstart-pool-0
  namespace: default
spec:
  eksNodegroupName: node-group-0
  remoteAccess:
    sshKeyName: <my-ssh-key>
```
**What did you expect to happen:**
Should be able ssh into the workers in private subnet using bastion.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 0.6.5
- Kubernetes version: (use `kubectl version`): 1.19
