### ISSUE TITLE
 ELB deletions: timed out waiting for the condition

### ISSUE THREAD

**Issue by haho16** [kubernetes-sigs/cluster-api-provider-aws#2449]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
First of all, thanks to all for your work. The project is very interesting and it is clear there is a lot of effort involved in it :). 
I am testing the creation of an AWS workload cluster from an existing EKS cluster and using existing VPC/subnet infra. 

The cluster is created correctly, however during deletion I am reaching a blocker when trying to delete the LoadBalancer. It seems the CLB is deleted before the actual step of CLB deletion occurs. Here are the steps:

- Create a cluster
- Use `kubectl delete cluster capi-quickstart -ndefault` to delete it
- All is deleted correctly, until it reaches the AWSCluster section, where it does delete the CLB but then starts to complain it hits timeout:
```
E0601 08:51:01.201142       1 awscluster_controller.go:167] controllers/AWSCluster "msg"="error deleting load balancer" "error"="failed to wait for \"capi-quickstart\" ELB deletions: timed out waiting for the condition" "awsCluster"="capi-quickstart" "cluster"="capi-quickstart" "namespace"="default" 
```
This then blocks cluster deletion. 

Is there a way I can force this deletion on API level, as the CLB is correctly deleted but the cluster seems to enter a loop still trying to delete it?

**What did you expect to happen:**

Cluster deletion order to be preserved and not reach timeout errors.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Here is my cluster config:
```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-quickstart
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: capi-quickstart
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: capi-quickstart-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: capi-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: capi-quickstart
  namespace: default
spec:
  networkSpec:
    vpc:
      id: [...]
    subnets:
      [...]
  bastion:
    enabled: true
  additionalTags:
    [...]
  region: us-west-2
  sshKeyName: [...]
  controlPlaneLoadBalancer:
    scheme: internal
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSMachineTemplate
    name: capi-quickstart-control-plane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  replicas: 3
  version: v1.19.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      additionalTags:
         [...]
      instanceType: t3.small
      sshKeyName: [...]
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  clusterName: capi-quickstart
  replicas: 3
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: capi-quickstart-md-0
      clusterName: capi-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: capi-quickstart-md-0
      version: v1.19.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      additionalTags:
         [...]
      instanceType: t3.small
      sshKeyName: [...]
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capi-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}'
---
apiVersion: addons.cluster.x-k8s.io/v1alpha3
kind: ClusterResourceSet
metadata:
  name: capi-quickstart-1-crs-0
  namespace: default
spec:
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capi-quickstart
  resources:
  - kind: ConfigMap
    name: calico-cni
  - kind: ConfigMap
    name: nginx-ingress
```

**Environment:**

- Cluster-api-provider-aws version:
```
Installing cert-manager Version="v1.1.0"
Waiting for cert-manager to be available...
Installing Provider="cluster-api" Version="v0.3.17" TargetNamespace="capi-system"
Installing Provider="bootstrap-kubeadm" Version="v0.3.17" TargetNamespace="capi-kubeadm-bootstrap-system"
Installing Provider="control-plane-kubeadm" Version="v0.3.17" TargetNamespace="capi-kubeadm-control-plane-system"
Installing Provider="infrastructure-aws" Version="v0.6.6" TargetNamespace="capa-system"
```
- Kubernetes version: (use `kubectl version`): client 1.18.8 / server 1.19.8
- OS (e.g. from `/etc/os-release`): debian 10
