### ISSUE TITLE
When running clusterawsadm bootstrap IAM for EKS clusters ExtraPolicyAttachments are not working properly

### ISSUE THREAD

**Issue by martin-ducar-gd** [kubernetes-sigs/cluster-api-provider-aws#2462]
/kind bug

**What steps did you take and what happened:**
Bootstrap config
```yaml
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
kind: AWSIAMConfiguration
spec:
  bootstrapUser:
    enable: true
  eks:
    enable: true
    iamRoleCreation: false # Set to true if you plan to use the EKSEnableIAM feature flag to enable automatic creation of IAM roles
    defaultControlPlaneRole:
      disable: false # Set to false to enable creation of the default control plane role
    managedMachinePool:
      disable: false # Set to false to enable creation of the default node role for managed machine pools
  nodes:
    ExtraPolicyAttachments:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
```
Than generate CF template
```sh
clusterawsadm bootstrap iam print-cloudformation-template --config bootstrap.config.yaml
```

**What did you expect to happen:**
I expect eks-nodegroup role to have attached this policy but its not there as can be seen here:
```yaml
  AWSIAMRoleEKSNodegroup:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
            - eks.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      RoleName: eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
    Type: AWS::IAM::Role
```

**Anything else you would like to add:**
That additional policy is not found anywhere, maybe I'm missing something but following https://cluster-api-aws.sigs.k8s.io/topics/using-clusterawsadm-to-fulfill-prerequisites.html and that is not working also https://cluster-api-aws.sigs.k8s.io/crd/clusterawsadm.html is completely empty page for me so can't see If there are other options specific to EKS without checking the code

**Environment:**

- Cluster-api-provider-aws version: 
```sh
$ clusterawsadm version
clusterawsadm version: &version.Info{Major:"0", Minor:"6", GitVersion:"v0.6.5", GitCommit:"c7c8ae1ee071afbb33c3b45b0f9adbea149581ce", GitTreeState:"clean", BuildDate:"2021-04-15T17:03:17Z", GoVersion:"go1.13.15", AwsSdkVersion:"v1.36.26", Compiler:"gc", Platform:"darwin/amd64"}
```
- Kubernetes version: (use `kubectl version`): not relevant
- OS (e.g. from `/etc/os-release`):  19.6.0 Darwin
