### ISSUE TITLE
invalid type for io.x-k8s.cluster.infrastructure.v1alpha3.AWSMachinePool.spec.subnets: got "string", expected "map"

### ISSUE THREAD

**Issue by chessman** [kubernetes-sigs/cluster-api-provider-aws#2464]
/kind bug

**What steps did you take and what happened:**

I followed steps from https://cluster-api-aws.sigs.k8s.io/topics/machinepools.html

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachinePool
metadata:
  name: capi-test-mp-0
  namespace: default
spec:
  availabilityZones:
  - "eu-central-1"
  awsLaunchTemplate:
    instanceType: t3.large
    sshKeyName: capi
  maxSize: 10
  minSize: 1
  subnets:
    - "eu-central-1a"
```

After applying the configuration, I got

```
error validating "capi-test.yaml": error validating data: ValidationError(AWSMachinePool.spec.subnets[0]): invalid type for io.x-k8s.cluster.infrastructure.v1alpha3.AWSMachinePool.spec.subnets: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```

**What did you expect to happen:**

No error as it is the same as in the provided documentation.

**Anything else you would like to add:**

This configuration works:

```
subnets:
  - id: eu-central-1a
```

`Subnets` field has `[]infrav1.AWSResourceReference` type, so it requires an object, not a string.

**Environment:**

- Cluster-api-provider-aws version: v0.6.6
- Kubernetes version: (use `kubectl version`): v1.21.1
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 11 (bullseye)
