### ISSUE TITLE
EKS cluster securityGroupOverrides not working

### ISSUE THREAD

**Issue by martin-ducar-gd** [kubernetes-sigs/cluster-api-provider-aws#2466]
/kind bug

**What steps did you take and what happened:**
Deployed EKS cluster using definition like this:
```yaml
...
  networkSpec:
    securityGroupOverrides:
      controlplane: sg-056365b8ae52359bb
      node: sg-0f2145082af145cdb
      lb: sg-056365b8ae52359bb
      apiserver-lb: sg-056365b8ae52359bb
      bastion: sg-056365b8ae52359bb
      node-eks-additional: sg-056365b8ae52359bb
```
but the controll plane still has default generated SG and same goes for nodegroup this is related also to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2465
```sh
$ aws eks describe-cluster --name default_mgmt01-control-plane --region us-east-1 | jq '.cluster.resourcesVpcConfig.securityGroupIds, .cluster.resourcesVpcConfig.clusterSecurityGroupId'
[
  "sg-0518d3e0cecee51e0"
]
"sg-06fcebd35dbc4d445"
$ aws ec2 get-launch-template-data --instance-id i-<redacted> | jq '.LaunchTemplateData.NetworkInterfaces[] | .Groups'
[
  "sg-06fcebd35dbc4d445"
]
[
  "sg-06fcebd35dbc4d445"
]
```
As can be seen nodes have still same SG as controllplane and again not one selected

**What did you expect to happen:**
controlplane to have `sg-056365b8ae52359bb` and node to have `sg-0f2145082af145cdb, sg-056365b8ae52359bb`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
```sh
$ kubectl get deploy -n capa-system capa-controller-manager -o yaml | grep cluster-api-aws-controller
        image: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller:v0.6.6
```
- Kubernetes version: (use `kubectl version`): 
```sh
$ kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:39569
KubeDNS is running at https://127.0.0.1:39569/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```
- OS (e.g. from `/etc/os-release`): 
```sh
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
