### ISSUE TITLE
Spot Instance Support for AWSManagedMachinePool

### ISSUE THREAD

**Issue by cabrinha** [kubernetes-sigs/cluster-api-provider-aws#2523]
/kind feature

**Describe the solution you'd like**
I'd like to use AWSManagedMachinePool / MachinePool with spot instances.

**Environment:**

- Cluster-api-provider-aws version: v6.5.0
- Kubernetes version: (use `kubectl version`): v1.19
- OS (e.g. from `/etc/os-release`): amazon linux 2

**Comment by voor** [comment]
Referencing https://www.github.com/kubernetes-sigs/cluster-api/tree/master/docs%2Fproposals%2F20200330-spot-instances.md

**Comment by pydctw** [comment]
Spot Instance support is already available with AWSManagedMachinePool + MachinePool flavor by specifying `capacityType` in AWSManagedMachinePool spec.

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: eks-pool-0
spec:
  capacityType: spot
  ...
```

What are remaining tasks for the issue? (I may lack context on this, hence asking)
