### ISSUE TITLE
Wrong role name assigned to role in AWSManagedMachinePool

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/cluster-api-provider-aws#2597]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I created a EKS cluster with a managed node group. The IAM role name assigned to the AWSManagedMachine pool was `eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io`, but that group that role was never created. Instead, CAPA/CAPI created a role called `nodes.cluster-api-provider-aws.sigs.k8s.io`. Once I manually created a role with the name `eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io` the node group was provisioned. 

**What did you expect to happen:**
I expected it to create an EKS cluster with 1 managed node group.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v0.6.6
- Kubernetes version: (use `kubectl version`): 1.20.4
- OS (e.g. from `/etc/os-release`): OSX

**Comment by richardcase** [comment]
Thanks @jicowan - i'll look into this.

**Comment by richardcase** [comment]
This is strange as the e2e tests cover creating a managed machine pool and scaling it up and down.

**Comment by richardcase** [comment]
I am investigating this and trying to re-create:

/assign
/lifecycle active

**Comment by richardcase** [comment]
@jicowan - after investigation, this it isn't a bug but a result of bad docs/ux on our part. I think we could give a more descriptive error with a hint of the issue.

In CAPA for EKS clusters, all clusters/nodegroups by default share the same IAM roles (unless you explicitly enable IAM roles per cluster). In the case of managed machine pools the default role is `eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io`.   The default roles are created when you do `clusterawsadm bootstrap iam create-cloudformation-stack` but as EKS and machine pools are experimental features you need to use a config file to enable the creation of any IAM related artefacts for these features when you do `create-cloudformation-stack`.

The [documentation in this area](https://cluster-api-aws.sigs.k8s.io/topics/using-clusterawsadm-to-fulfill-prerequisites.html#with-eks-support) needs to be improved.  As an example, create a file called `eks.config` and add the following as contents: 

```yaml
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1alpha1
kind: AWSIAMConfiguration
spec:
  bootstrapUser:
    enable: true
  eks:
    enable: true
    iamRoleCreation: false # Set to true if you plan to use the EKSEnableIAM feature flag to enable automatic creation of IAM roles
    defaultControlPlaneRole:
      disable: false # Set to false to enable creation of the default control plane role
    managedMachinePool:
      disable: false # Set to false to enable creation of the default node pool role
```

And then you can run:

```bash
clusterawsadm bootstrap iam create-cloudformation-stack --config eks.config
```

If you are interested in the IAM roles per cluster feature, have a look [here](https://cluster-api-aws.sigs.k8s.io/topics/eks/enabling.html#enabling-the-eks-features) to see how to enable it.
