### ISSUE TITLE
publicIP field in AWSMachine does not work

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2653]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

As reported on slack: https://kubernetes.slack.com/archives/CD6U2V71N/p1628391133050900

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sayantani11** [comment]
@sedefsavas If I can get some help and insight on the task, I could help.

**Comment by dilyevsky** [comment]
The way we've been working around this is with:

```
      subnet:
        filters:
        - name: "map-public-ip-on-launch"
          values: ["true"]
```

Indeed if you just set publicIP the provider will not automatically pick a subnet with public IPs.
