### ISSUE TITLE
Managed machine pool error: onDemand field is immutable 

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#2712]
/kind bug
/area provider/eks
/priority critical-urgent

**What steps did you take and what happened:**
Attempted to create a managed machine pool with the following spec:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSManagedMachinePool
metadata:
  name: "capi-managed-test-pool-0"
spec:
  remoteAccess:
    sshKeyName: "capi-management"
```

It fails with the following error:

```bash
E0826 09:26:08.592397       8 controller.go:304] controller-runtime/manager/controller/machinepool "msg"="Reconciler error" "error"="admission webhook \"validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io\" denied the request: AWSManagedMachinePool.infrastructure.cluster.x-k8s.io \"capi-managed-test-pool-0\" is invalid: spec.capacityType: Invalid value: \"onDemand\": field is immutable" "name"="capi-managed-test-pool-0" "namespace"="default" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachinePool" 
```

**What did you expect to happen:**

I expect this to succeed

**Environment:**

- Cluster-api-provider-aws version: main branch (post 0.7.0)
