### ISSUE TITLE
AWSClusterControllerIdentity panics when AllowedNamespaces is nil

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-aws#2880]
/kind bug

**What steps did you take and what happened:**
Creating AWSClusterControllerIdentity with
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSClusterControllerIdentity
metadata:
  name: default
```

and then updating the namespaces like this
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: AWSClusterControllerIdentity
metadata:
  name: default
spec:
  allowedNamespaces: {}
```
panics due to missing nil check here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/986262a0bac2448116779f237a3615f7a367e864/api/v1beta1/awsclustercontrolleridentity_webhook.go#L91

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/priority critical-urgent
/milestone v1.0.x
