### ISSUE TITLE
Kustomize based install for CAPA

### ISSUE THREAD

**Issue by szucsitg** [kubernetes-sigs/cluster-api-provider-aws#2986]
/kind feature

**Describe the solution you'd like**
I'd like to install CAPA with pure* Kustomize based install, so I can manage it with GitOps based tooling declaratively.
Currently with heavy reliance on envvar substitution it's very tedious and error-prone to fix all references within the manifest.
I attached my current working solution, which still might have some issues.

_\* = IAM roles cannot be deployed that way, but we can manage its deployment programatically through CDK._

**Anything else you would like to add:**
Some issues that you can notice from the templating:
* `iam.amazonaws.com/role` annotation in Deployment, which I believe is deprecated
* many name overrides as now (1.0+) namespace prefix seems to be appended dynamically to multiple resources (ServiceAccount, RoleBinding, ClusterRoleBinding...)
* mandatory mount of bootstrap credential secret resource, even if we fully rely on IAM Roles for Service Accounts

Current working deployment file:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: gcr.io/k8s-staging-cluster-api-aws/cluster-api-aws-controller
  newTag: v1.1.0

resources:
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/config/default/?ref=v1.1.0

patches: #--leader-elect
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--feature-gates=EKS=true,EKSEnableIAM=true,EKSAllowAddRoles=false,EKSFargate=false,MachinePool=true,EventBridgeInstanceState=false,AutoControllerIdentityCreator=false"]
    - op: replace
      path: /spec/template/spec/serviceAccountName
      value: capa-controller-manager
    - op: replace
      path: /spec/template/spec/affinity/nodeAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/preference/matchExpressions/0/key
      value: node-role.kubernetes.io/control-plane
    - op: replace
      path: /spec/template/metadata/annotations
      value: {"iam.amazonaws.com/role": "arn:aws:iam::1234567890:role/controllers.cluster-api-provider-aws.sigs.k8s.io"}
  target:
    kind: Deployment
    labelSelector: "control-plane=capa-controller-manager"
- patch: |-
    - op: replace
      path: /metadata/annotations
      value: {"eks.amazonaws.com/role-arn": "arn:aws:iam::1234567890:role/controllers.cluster-api-provider-aws.sigs.k8s.io"}
  target:
    kind: ServiceAccount
    labelSelector: "control-plane=controller-manager"
- patch: |-
    - op: replace
      path: /subjects/0/name
      value: capa-controller-manager
    - op: replace
      path: /subjects/0/namespace
      value: capa-system
  target:
    kind: ClusterRoleBinding
    labelSelector: "cluster.x-k8s.io/provider=infrastructure-aws"
- patch: |-
    - op: replace
      path: /subjects/0/name
      value: capa-controller-manager
    - op: replace
      path: /subjects/0/namespace
      value: capa-system
  target:
    kind: RoleBinding
    labelSelector: "cluster.x-k8s.io/provider=infrastructure-aws"

secretGenerator:
- name: capa-manager-bootstrap-credentials
  namespace: capa-system
  behavior: replace
  envs:
    - credentials.env
  type: Opaque
  options:
    disableNameSuffixHash: true
    labels:
      cluster.x-k8s.io/provider: infrastructure-aws
```

credentials.env for reproducibility:
```
AWS_B64ENCODED_CREDENTIALS=mysecretcredentials
```

**Environment:**

- Cluster-api-provider-aws version: 1.1.0
- Kubernetes version: (use `kubectl version`): 1.21.2
- OS (e.g. from `/etc/os-release`): N/A

**Comment by richardcase** [comment]
@szucsitg - a [CAPI provider operator](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20201020-capi-provider-operator.md) is being worked on that will make the install and management of providers declarative and GitOps friendly. To give an example from the proposal to use CAPA:

```yaml
apiVersion: v1
kind: Secret
metadata:
 name: aws-variables
 namespace: capa-system
type: Opaque
data:
 AWS_REGION: ...
 AWS_ACCESS_KEY_ID: ...
 AWS_SECRET_ACCESS_KEY: ...
---
apiVersion: management.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: aws
 namespace: capa-system
spec:
 version: v0.6.0
 secretName: aws-variables
 manager:
   # These top level controller manager flags, supported by all the providers.
   # These flags come with sensible defaults, thus requiring no or minimal
   # changes for the most common scenarios.
   metricsAddress: ":8181"
   syncPeriod: 660
 fetchConfig:
   url: https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases
 deployment:
   containers:
   - name: manager
     args:
         # These are controller flags that are specific to a provider; usage
         # is reserved for advanced scenarios only.
         awscluster-concurrency: 12
         awsmachine-concurrency: 11
```
