### ISSUE TITLE
Support running with public subnets only

### ISSUE THREAD

**Issue by khoa-hatch** [kubernetes-sigs/cluster-api-provider-aws#2997]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Allows:
- creating VPC with only public subnets
- place the managed nodes group to those public subnets if no private subnets defined in the cluster spec.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
We have an usecase to create an EKS cluster with only public subnets.
We need to maintain 1 to 1 tcp connection mapping between our pods and clients like:
```
pod 1 <--- tcp port 30000 over internet ----> client 1
pod 2 <--- tcp port 30001 over internet ----> client 2
...
```
A nodeport service is created for each pod to expose the pod publicly over internet.
With that requirement, the worker ec2 instances have to run in public subnets and we don't need private subnets (and natgw) at all.

Example:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test
  namespace: capi-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.28.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: test-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: test-control-plane
  namespace: capi-system
spec:
  region: eu-north-1
  sshKeyName: sshkey
  version: v1.21.7
  associateOIDCProvider: true
  bastion:
    allowedCIDRBlocks:
    - 0.0.0.0/0
    enabled: false
  disableVPCCNI: false
  addons:
  - name: "vpc-cni"
    version: "v1.10.1-eksbuild.1"
    conflictResolution: "overwrite"
  endpointAccess:
    public: true
  network:
    vpc:
      cidrBlock: "10.10.0.0/16"
    subnets:
    - availabilityZone: eu-north-1a
      cidrBlock: "10.10.0.0/21"
      isPublic: true
    - availabilityZone: eu-north-1b
      cidrBlock: "10.10.8.0/21"
      isPublic: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: test-pool-0
  namespace: capi-system
spec:
  clusterName: test
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: test-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: test-pool-0
  namespace: capi-system
spec:
  remoteAccess:
    public: true
    sshKeyName: sshkey
  scaling:
    minSize: 1
    maxSize: 2
```

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
