### ISSUE TITLE
EKS bastion security-group is created when bastion is disabled

### ISSUE THREAD

**Issue by abhinavnagaraj** [kubernetes-sigs/cluster-api-provider-aws#3026]
/kind bug

**What steps did you take and what happened:**
Create an EKS cluster with bastion disabled
```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-quickstart-control-plane
  namespace: default
spec:
  bastion:
    enabled: false
  region: us-east-1
  sshKeyName: default
  version: v1.21.0
```
**What did you expect to happen:**
The security group '**capi-eks-quickstart-bastion**' should not be created.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: 1.2.0
- Kubernetes version: (use `kubectl version`): 1.21
- OS (e.g. from `/etc/os-release`):
