### ISSUE TITLE
Nightly manifests overrides types from CAPI v1beta1 manifests

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api-provider-aws#3057]
/kind bug

**What steps did you take and what happened:**

Right now (https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/671166141dbfb2fa7ec30f5dd7625f12ed7b6ba8/test/e2e/data/e2e_conf.yaml), in `test/e2e/data/e2e_conf.yaml` file, there are both v1beta1 release manifests defined (here version v1.0.2) and nightly manifests (v1.1.99). Right now, if both of those manifests contains e.g. the same CRDs, nightlies will override the v1beta1 manifests. This effectively breaks testing against CAPI release manifests in favor of nightly builds (which may not be stable and may increase tests flakyness etc.).

```yaml
providers:
  - name: cluster-api
    type: CoreProvider
    versions:
     ...
      - name: v1.0.2
        value: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.0.2/core-components.yaml"
        type: "url"
        contract: v1beta1
        files:
          - sourcePath: "./shared/v1beta1/metadata.yaml"
        replacements:
          - old: "imagePullPolicy: Always"
            new: "imagePullPolicy: IfNotPresent"
          - old: --metrics-bind-addr=127.0.0.1:8080
            new: --metrics-bind-addr=:8080
      - name: v1.1.99 # next;
        value: "https://storage.googleapis.com/artifacts.k8s-staging-cluster-api.appspot.com/components/nightly_main_20211122/core-components.yaml"
        type: "url"
        contract: v1beta1
        files:
        - sourcePath: "./shared/v1beta1/metadata.yaml"
```

**What did you expect to happen:**

Nightly types do not override release types to be able to reliably use release manifests.

**Anything else you would like to add:**

Found while working on #2271, trying to figure out why after updating from `v1.0.2` to `v1.1.0-beta1` Ignition-related fields are still not available.
