### ISSUE TITLE
Bastion host not created

### ISSUE THREAD

**Issue by lackhoa** [kubernetes-sigs/cluster-api-provider-aws#3082]
/kind bug

**What steps did you take and what happened:**
I enabled bastion host in the AWSManagedControlPlane `kv-test-stream-control-plane`, and created the cluster. However the bastion instance wasn't created, only the security group.

**What did you expect to happen:**
Bastion instance created, so that I can ssh to the worker nodes.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v1.2.0.
- Kubernetes version: (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}`
- OS (e.g. from `/etc/os-release`): `CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"`

**Config:**
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: kv-test-stream
  namespace: capi-system
  labels:
    csi: external
    cluster_fqdn: kv-test-stream.dev.hatch.live
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 172.28.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: kv-test-stream-control-plane
  infrastructureRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: AWSManagedControlPlane
    name: kv-test-stream-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: kv-test-stream-control-plane
  namespace: capi-system
spec:
  eksClusterName: kv-test-stream
  region: eu-west-1
  sshKeyName: common-key
  version: v1.21.7
  associateOIDCProvider: true
  bastion:
    allowedCIDRBlocks:
    - 0.0.0.0/0
    enabled: true
  disableVPCCNI: false
  imageLookupBaseOS: ubuntu-20.04
  imageLookupOrg: '919550398598'
  imageLookupFormat: 'capa-ami-{{.BaseOS}}-{{.K8sVersion}}-*'
  addons:
  - name: "vpc-cni"
    version: "v1.10.1-eksbuild.1"
    conflictResolution: "overwrite"
  endpointAccess:
    public: true
  network:
    vpc:
      cidrBlock: "10.10.0.0/16"
    subnets:
    - availabilityZone: eu-west-1a
      cidrBlock: "10.10.0.0/21"
      isPublic: true
    - availabilityZone: eu-west-1b
      cidrBlock: "10.10.8.0/21"
      isPublic: true
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: kv-test-stream-pool-0
  namespace: capi-system
spec:
  clusterName: kv-test-stream
  replicas: 1
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: EKSConfig
          name: kv-test-stream
      clusterName: kv-test-stream
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachinePool
        name: kv-test-stream-pool-0
      version: v1.21.7
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachinePool
metadata:
  name: kv-test-stream-pool-0
  namespace: capi-system
spec:
  awsLaunchTemplate:
    instanceType: t3.medium
    sshKeyName: common-key
    imageLookupBaseOS: ubuntu-20.04
    imageLookupOrg: '919550398598'
    imageLookupFormat: 'capa-ami-{{.BaseOS}}-{{.K8sVersion}}-*'
    rootVolume:
      size: 50
      type: gp3
    additionalSecurityGroups:
      
  minSize: 1
  maxSize: 2
---
kind: EKSConfig
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
metadata:
  name: kv-test-stream
spec:
  kubeletExtraArgs:
    cpu-manager-policy: 'static'
    allowed-unsafe-sysctls: 'net.*'
    eviction-soft: 'memory.available<300Mi'
    eviction-soft-grace-period: 'memory.available=1m'
    eviction-hard: 'memory.available<150Mi,imagefs.available<15%,nodefs.available<10%,nodefs.inodesFree<5%'
    kube-reserved: 'cpu=250m,memory=250Mi,ephemeral-storage=1Gi'
    system-reserved: 'cpu=250m,memory=250Mi,ephemeral-storage=2Gi'
```

**Log dump from `capa-controller-manager`:**

https://gist.github.com/lackhoa/a95d32761e0e8b01980972cadd082a74
