### ISSUE TITLE
Can't create additional nonRootVolumes for Etcd Persistency

### ISSUE THREAD

**Issue by dntosas** [kubernetes-sigs/cluster-api-provider-aws#3105]
/kind bug

**What steps did you take and what happened:**
I am creating a self-managed AWSCluster successfully. Then I need to attach more `nonRootVolumes` to the instances of the Control Plane in order to utilize them for Etcd persistency. Unfortunately, creation of either `AWSMachine` or `AWSMachineTemplate` fails either on validation or CAPA panics with the following error:
```
2022/01/27 06:29:02 http: panic serving 10.106.7.244:37242: runtime error: invalid memory address or nil pointer dereference
goroutine 12053 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1801 +0xb9
panic({0x20680e0, 0x3d53030})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
sigs.k8s.io/cluster-api-provider-aws/api/v1beta1.(*AWSMachine).validateNonRootVolumes(0xc00003c2c0)
	/workspace/api/v1beta1/awsmachine_webhook.go:172 +0xe6
sigs.k8s.io/cluster-api-provider-aws/api/v1beta1.(*AWSMachine).ValidateCreate(0xc00003c2c0)
	/workspace/api/v1beta1/awsmachine_webhook.go:54 +0x156
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*validatingHandler).Handle(_, {_, _}, {{{0xc000d8f4d0, 0x24}, {{0xc000ed1bc0, 0x1f}, {0xc000c78850, 0x7}, {0xc000c78860, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0-beta.0.0.20211110210527-619e6b92dab9/pkg/webhook/admission/validator.go:71 +0x239
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc000d8f4d0, 0x24}, {{0xc000ed1bc0, 0x1f}, {0xc000c78850, 0x7}, {0xc000c78860, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0-beta.0.0.20211110210527-619e6b92dab9/pkg/webhook/admission/webhook.go:146 +0xa2
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc00026ca80, {0x7f2853688638, 0xc000f78a00}, 0xc000c32100)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0-beta.0.0.20211110210527-619e6b92dab9/pkg/webhook/admission/http.go:99 +0xef6
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f2853688638, 0xc000f78a00}, 0xc000f78a00)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:40 +0xd4
net/http.HandlerFunc.ServeHTTP(0x282edd8, {0x7f2853688638, 0xc000f78a00}, 0x40ce34)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x282edd8, 0xc00011f180}, 0xc000c32100)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101 +0x92
net/http.HandlerFunc.ServeHTTP(0xc00003a7c0, {0x282edd8, 0xc00011f180}, 0xe0)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x282edd8, 0xc00011f180}, 0xc000c32100)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:76 +0xa2
net/http.HandlerFunc.ServeHTTP(0xc074accbbab55362, {0x282edd8, 0xc00011f180}, 0xc00011f180)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000b3b6c2, {0x282edd8, 0xc00011f180}, 0xc000c32100)
	/usr/local/go/src/net/http/server.go:2424 +0x149
net/http.serverHandler.ServeHTTP({0x2820e00}, {0x282edd8, 0xc00011f180}, 0xc000c32100)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0002ddea0, {0x283ac78, 0xc000869080})
	/usr/local/go/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3033 +0x4e8
```

Attaching my YAML specs:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: test
spec:
  template:
    spec:
      iamInstanceProfile: IAM
      instanceType: TYPE
      nonRootVolumes:
        - size: 8
          deviceName: "/dev/sdb"
```
Tried different flavours of configuring `nonRootVolumes` without success.

**What did you expect to happen:**
Create and attach an additional EBS.

**Environment:**
- Cluster-api-provider-aws version: 1.2.0
- Kubernetes version: (use `kubectl version`): 1.23.2
- OS (e.g. from `/etc/os-release`): ubuntu20.04

**Comment by dntosas** [comment]
nvm, that happened because of some configuration on kubeAdmControlPlane missing ^^

posting for reference in case anyone ends up in here:
```yaml
    preKubeadmCommands:
    - if [ -d "/var/lib/etcd/lost+found" ]; then rm -Rf /var/lib/etcd/lost+found; fi
    diskSetup:
      filesystems:
        - device: /dev/nvme1n1
          label: etcd
          filesystem: ext4
          partition: auto
      partitions:
        - device: /dev/nvme1n1
          layout: true
          overwrite: false
          tableType: mbr
    mounts:
      - - LABEL=etcd
        - /var/lib/etcd
```
