### ISSUE TITLE
sts_regional_endpoints support

### ISSUE THREAD

**Issue by matlemb** [kubernetes-sigs/cluster-api-provider-aws#3477]
/kind feature

**Describe the solution you'd like**
When using `ClusterRoleIdentity` in an air-gapped environment an AWS endpoint is needed to call the STS service to use AssumeRole. By default there is no option to tell `capa` to use an regional endpoint other than manually editing the `capa` deployment and add the following environment variables:

```YAML
apiVersion: apps/v1
kind: Deployment
  name: capa-controller-manager
  namespace: capa-system
spec:
  template:
    spec:
      containers:
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_REGION
          value: <REGION>
        - name: AWS_DEFAULT_REGION
          value: <REGION>
```
It would be great if these environments would be set conditionally by setting appropriate values through the `.cluster-api/clusterctl.yaml` and [infrastructure-components.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/download/v1.4.1/infrastructure-components.yaml).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 1.4.1
- Kubernetes version: (use `kubectl version`): 1.23.3
- OS (e.g. from `/etc/os-release`): ubuntu-20.04

<sub>Matthias Lembcke <[matthias.lembcke@mercedes-benz.com](mailto:matthias.lembcke@mercedes-benz.com)>, Daimler TSS GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>
