### ISSUE TITLE
Add a required field to SubnetSpec to use as listMapKey in SSA

### ISSUE THREAD

**Issue by pydctw** [kubernetes-sigs/cluster-api-provider-aws#3528]
/kind feature

**Describe the solution you'd like**
While validating a fix for co-authored slice issue in ClusterClass, 
* Issue: https://github.com/kubernetes-sigs/cluster-api/issues/6320
* Fix: https://github.com/kubernetes-sigs/cluster-api/pull/6495
* Doc: [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/)

It was discovered that we need a required field in [SubnetSpec](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/api/v1beta1/network_types.go#L218) that can be used as a listMapKey with Server Side Apply. This fields needs to be unique in the list.

```yaml
// +listType=map
// +listMapKey=some-unique-key
Subnets Subnets `json:"subnets,omitempty"
```

I tried to use `id` as a key but got the following error as it is not a required field.
```sh
$ kubectl apply -f config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
The CustomResourceDefinition "awsclusters.infrastructure.cluster.x-k8s.io" is invalid: spec.versions[2].schema.openAPIV3Schema.properties[spec].properties[network].properties[subnets].items.properties[id].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
```

All the existing fields in SubnetSpec are optional, hence cannot be used as a listMapKey.

**Anything else you would like to add:**
My initial proposal is to add `name` as a required field similar to CAPZ. This needs more investigation.

Feel free to suggest other ideas!

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sedefsavas** [comment]
/triage accepted
/priority important-soon
/milestone v1.5.0

Need to make sure whatever option we choose for this, the existing clusters+manifests used by users keep working. Making a field required might break things.
Will take a look more.

**Comment by pydctw** [comment]
@sedefsavas, @yastij and I experimented adding `uuid` field to SubnetSpec with a default with the intention of modifying it in a defaulting webhook.

```go
// SubnetSpec configures an AWS Subnet.
type SubnetSpec struct {
	// +kubebuilder:default=foo
	UUID string `json:"uuid"`

	// ID defines a unique identifier to reference this resource.
	ID string `json:"id,omitempty"`
         ...
```

Here is the generated CRD.
```yaml
subnets:
  description: Subnets configuration.
  items:
    description: SubnetSpec configures an AWS Subnet.
    properties:
      ...
      id:
        description: ID defines a unique identifier to reference
          this resource.
        type: string
      ...
      uuid:
        default: foo
        type: string
    required:
    - uuid
    type: object
  type: array
  x-kubernetes-list-map-keys:
  - uuid
  x-kubernetes-list-type: map
```

When applied, it added `uuid` default value to the spec.
```yaml
    subnets:
    - availabilityZone: us-west-1c
      cidrBlock: 10.1.0.0/24
      id: subnet-0588d98dd78abf69b
      isPublic: true
      natGatewayId: nat-0cee374112fce9c64
      routeTableId: rtb-033ead8b2819b5f41
      tags:
        Name: unmanaged-public-sn
        kubernetes.io/cluster/um-ec2-cc-cluster: shared
        kubernetes.io/cluster/um-ec2-cluster: shared
        kubernetes.io/role/elb: "1"
      uuid: foo ⬅️
      ...
```
