### ISSUE TITLE
docs: AWSIAMConfiguration for bootstrap-manager-account has incorrect namespace for allowing sts:AssumeRoleWithWebIdentity with OIDC auth

### ISSUE THREAD

**Issue by banthaherder** [kubernetes-sigs/cluster-api-provider-aws#3554]
/kind bug

**What steps did you take and what happened:**
Following the docs for Multitenancy setup causes the capa controller to produce a 403 during an attempt to assume a role when it tries to standup a new managed cluster in the managed account. This is because the bootstrap AWSIAMConfiguration resource incorrectly records the namespace of the capa-controller-manager ServiceAccount as capa-system. The entire guide create capa/capi resources in the capi-providers namespace and the capa-system namespace doesn't exist when following the steps provided.

```
envsubst > bootstrap-manager-account.yaml << EOL
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSIAMConfiguration
spec:
  eks: # This section should be changed accordingly to your requirements
    iamRoleCreation: false
    managedMachinePool:
      disable: true
    fargate:
      disable: false
  clusterAPIControllers: # This is the section that really matter
    disabled: false
    extraStatements:
    - Action:
      - "sts:AssumeRole"
      Effect: "Allow"
      Resource: ["arn:aws:iam::${AWS_MANAGED_ACCOUNT_ID}:role/controllers.cluster-api-provider-aws.sigs.k8s.io"]
    trustStatements:
    - Action:
      - "sts:AssumeRoleWithWebIdentity"
      Effect: "Allow"
      Principal:
        Federated:
        - "arn:aws:iam::${AWS_MANAGER_ACCOUNT_ID}:oidc-provider/oidc.eks.${AWS_REGION}.amazonaws.com/id/${OIDC_PROVIDER_ID}"
      Condition:
        "ForAnyValue:StringEquals":
          "oidc.eks.${AWS_REGION}.amazonaws.com/id/${OIDC_PROVIDER_ID}:sub":
            - system:serviceaccount:capa-system:capa-controller-manager
            - system:serviceaccount:capa-eks-control-plane-system:capa-eks-control-plane-controller-manager # Include if also using EKS
EOL
```

**What did you expect to happen:**
I expected the newly created manager cluster to be able to assume the the role into the managed account and be able to manage resources there. 

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-aws version: N/A
- Kubernetes version: (use `kubectl version`): N/A 
- OS (e.g. from `/etc/os-release`): N/A
