### ISSUE TITLE
Inconsistent `kubernetes.io/cluster/` tag usage with EKS

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#3572]
/kind bug
/help
/good-first-issue
/priority backlog
/triage accepted

**What steps did you take and what happened:**
When creating an EKS cluster that then has services of type load balancer within it the `kubernetes.io/cluster/` tags are not consistent across the EKS service and tags for resources created by the CCM, such as ELB/NLBs.

Create a cluster with the following manifest:

```yaml
---
apiVersion: cluster.x-k8s.io/v1alpha4
kind: Cluster
metadata:
  name: "capi-managed-test"
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "capi-managed-test-control-plane"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: "capi-managed-test-control-plane"
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
metadata:
  name: "capi-managed-test-control-plane"
spec:
  region: "eu-west-2"
  sshKeyName: "capi-management"
  version: "v1.21.0"
```

When the `Cluster` is **Ready** in the AWS console look at the tags for th EKS cluster and you'll see:

```
kubernetes.io/cluster/capi-managed-test=owned
```

Now create a service of type load balancer, so:

```
kubectl get secrets capi-managed-test-user-kubeconfig -o jsonpath={.data.value} | base64 -d > test.kubeconfig
kubectl apply --kubeconfig test.kubeconfig -f https://raw.githubusercontent.com/richardcase/cluster-api-provider-aws/1718_cleanup_lb/test/e2e/data/gcworkload.yaml`
```

Got to the EC2 service in the AWS console and look at the tags for the load balancer created and you'll see:

```
kubernetes.io/cluster/default_capi-managed-test-control-plane=owned
```

We should make the tag name on the EKS cluster be the "eksclustername"

**What did you expect to happen:**
I expect the `kubernetes.io/cluster/` tag name to be consistent/

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
