### ISSUE TITLE
For EKS, CAPI truncates the `version` field in AWSManagedControlPlane spec after apply

### ISSUE THREAD

**Issue by yogeek** [kubernetes-sigs/cluster-api-provider-aws#3594]
/kind bug

**What steps did you take and what happened:**

When setting k8s version for nodegroups in CAPI YAML manifest (`AWSManagedControlPlane.spec.template.spec.version`), EKS only allows MAJOR.MINOR (e.g. `1.22`) but ClusterAPI requires a "semantic version" MAJOR.MINOR.PATCH (e.g. 1.22.10)
- when setting 1.22 in the manifest, clusterAPI error is : `invalid: spec.template.spec.version: Invalid value: "v1.22": must be a valid semantic version`
- when setting 1.22.10, clusterAPI is ok **but** it modifies the final resources in K8S by truncating to `1.22` which causes a diff in gitops tool like ArgoCD (and if we ignore this diff, we will not be able to detect a version change later)

**What did you expect to happen:**

I expected ClusterAPI to not change a resource after it has been applied and to let version the same as declared in the initial manifest (in GIT). 

**Anything else you would like to add:**
This issue has already been discussed orally with @richardcase  

**Environment:**

- Cluster-api-provider-aws version: 1.4.1
- Kubernetes version: 1.22.9

**Comment by sedefsavas** [comment]
MachinePool version looks like having a validation check for updates as well, so should not be changeable to v1.22 looking at this:
https://github.com/kubernetes-sigs/cluster-api/blob/ef7172a853344d3b047fb0ace3f349079f3eef1f/exp/api/v1beta1/machinepool_webhook.go#L149

Could you confirm if MachinePool.spec.template.spec.version is set to v1.22?

**Comment by yogeek** [comment]
Hi @sedefsavas thanks for your help
Sorry, I mixed up resources and indeed, it is not `MachinePool` version which was truncated but `AWSManagedControlPlane` version
I am going to update the issue title accordingly

Here is the GIT manifest :
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: capi-eks-mycluster-control-plane
  namespace: mycluster-capi
spec:
  [...]
  version: v1.22.0
```
and the result after cluster api created the cluster /
```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  creationTimestamp: '2022-07-18T10:18:10Z'
name: capi-mycluster-kubeflow-control-plane
  namespace: mycluster-capi
  ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: Cluster
      name: capi-eks-mycluster
[...]
spec:
  version: v1.22
```
