### ISSUE TITLE
v1.5.0 fails to reconcile EKS cluster when cluster name is not same as eks control plane name

### ISSUE THREAD

**Issue by Jacobious52** [kubernetes-sigs/cluster-api-provider-aws#3698]
/kind bug

**What steps did you take and what happened:**

Starting in 1.5.0 with https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3598/files# if the EKS controlplane name is different the cluster name, reconciliation fails with `checking owner of bike is bike-cluster: **%!w(<nil>)**`

For an example:

Cluster object is called `bike-cluster`
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: bike-cluster
```

eksClusterName is `bike`
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: AWSManagedControlPlane
metadata:
  name: bike-control-plane
spec:
  eksClusterName: bike
```

This causes reconciliation to fail for the cluster
```
E0831 06:42:46.562913       1 controller.go:317] controller/awsmanagedcontrolplane "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane clusters/bike-control-plane: checking owner of bike is bike-cluster: %!w(<nil>)" "name"="bike-control-plane" "namespace"="clusters" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="AWSManagedControlPlane"
```

A temporary fix for end users is to manually add the cluster tag to the control plane resource, so that 
```
  additionalTags:
    "kubernetes.io/cluster/bike": "owned"
```

So that the control plane has both Cluster.Metadata.Name and AWSControlPlane.Spec.EKSClusterName`

![image](https://user-images.githubusercontent.com/12645162/187810315-d021d6c2-331a-4f39-a8ce-51bc3d55d03d.png)

**What did you expect to happen:**

The controller to either use Cluster Name or EKSClusterName consistently. 

**Anything else you would like to add:**

There is also a confusion about which name is correct to use in some places like
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3b32ca01169ab2cc1510398dd82b0669b9002db8/pkg/cloud/services/iamauth/reconcile.go#L33
and 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/3b32ca01169ab2cc1510398dd82b0669b9002db8/pkg/cloud/services/iamauth/reconcile.go#L80

```
I0901 00:45:06.128044       1 reconcile.go:33]  "msg"="Reconciling aws-iam-authenticator configuration"  "cluster-name"="bike-cluster"
I0901 00:45:06.225798       1 reconcile.go:80]  "msg"="Reconciled aws-iam-authenticator configuration"  "cluster-name"="bike"
```

**Environment:**

- Cluster-api-provider-aws version: 1.5.0
- Kubernetes version: (use `kubectl version`): 1.22
- OS (e.g. from `/etc/os-release`): N/A

**Comment by Skarlso** [comment]
I _might_ have found what's causing this... 🤞

**Comment by Skarlso** [comment]
Hm, I couldn't actually reproduce this.

@Jacobious52 Do you have a more involved example? I used this config:

```yaml
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "test-owner-tags"
spec:
  infrastructureRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "test-owner-tags-control-plane"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: "test-owner-tags-control-plane"
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "test-owner-tags-control-plane"
spec:
  eksClusterName: other
  network:
    vpc:
      availabilityZoneUsageLimit: 2
  region: "eu-central-1"
  version: "v1.22.0"

```

And got this in the logs:

```
I0907 11:28:16.175144      69 cluster.go:68]  "msg"="Found owned EKS cluster in AWS" "cluster-name"="other"
```
