### ISSUE TITLE
Userdata seems not working while using AWSManagedMachinePool

### ISSUE THREAD

**Issue by pixiono** [kubernetes-sigs/cluster-api-provider-aws#3700]
/kind bug

We are trying to build an EKS cluster with NodeGroups, using the AWSManagedMachinePool. Since we are in an almost airgapped environment (i.e. have no internet gateway or similar) we would like to configure a proxy. For this we need [to do a few things](https://aws.amazon.com/de/premiumsupport/knowledge-center/eks-http-proxy-configuration-automation/) on the node hostsystem and would like to upload a custom userdata script for this.

**What steps did you take and what happened:**
Since the documentation doesn't seem to cover our use case, we took inspiration from this repo and found the following: cluster-[template-eks-managed-machinepool-with-launch-template-only.yaml](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/test/e2e/data/eks/cluster-template-eks-managed-machinepool-with-launch-template-only.yaml) and replaced the variables with our values.

We also adjusted the Secret so it could be created easily:
```
apiVersion: v1
kind: Secret
metadata:
  name: "${CLUSTER_NAME}-pool-lt-0-userdata"
stringData:
  value: "USER_DATA"
type: Opaque
```

We didn't changed the value.

**What did you expect to happen:**
We have expected that, according to source code, the user data is stored either in the AWS Systems Manager or in the AWS Parameter Storage and is taken into account when the EC2 machines are started. We also connected to the EC2 instance via SSM and tried to download the userdata (without success): 
```
[root@ip-10-16-0-27 templates]# TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0  28297      0 --:--:-- --:--:-- --:--:-- 56000

[root@ip-10-16-0-27 templates]# curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/user-data/
*   Trying 169.254.169.254:80...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/user-data/ HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.79.1
> Accept: */*
> X-aws-ec2-metadata-token: AQAEACBMY6yMHCio_1I1z2Wqd2awDgT5mx7sIkewUo_J7nSlQ3QDDg==
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< X-Aws-Ec2-Metadata-Token-Ttl-Seconds: 21593
< Content-Type: application/octet-stream
< Accept-Ranges: none
< Last-Modified: Thu, 01 Sep 2022 13:01:45 GMT
< Content-Length: 2141
< Date: Thu, 01 Sep 2022 13:15:42 GMT
< Server: EC2ws
< Connection: close
<
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: text/x-shellscript; charset="us-ascii"
#!/bin/bash
set -ex
B64_CLUSTER_CA=< B64_CLUSTER_CA >
API_SERVER_URL=<API_SERVER_URL>
K8S_CLUSTER_DNS_IP=172.20.0.10
/etc/eks/bootstrap.sh default_capi-test-control-plane --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-01c52a64630ff492f,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=default_capi-test-pool-lt-0 --max-pods=17' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP --use-max-pods false
```

**Anything else you would like to add:**
We also tried to adjust the MachinePool like this (without any success):
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: "capi-test-pool-lt-0"
spec:
  clusterName: "capi-test"
  replicas: 2
  template:
    spec:
      cloudInit:
        insecureSkipSecretsManager: false
        secureSecretsBackend: secrets-manager
```

**Environment:**

- Cluster-api-provider-aws version: v1.5.0
- Kubernetes version: (use `kubectl version`): v1.23.7
- OS (e.g. from `/etc/os-release`):
