### ISSUE TITLE
Cannot create awscluster with additionalTags value containing spaces

### ISSUE THREAD

**Issue by cristian-radu** [kubernetes-sigs/cluster-api-provider-aws#3738]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I tried to create a cluster that has spec.additionalTags containg a tag with a value that has a space character in it and this failed.

**What did you expect to happen:**

I expected this to succeed. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: test-cluster
spec:
  additionalTags:
    Cost-Allocation: "My Value"
```

```
admission webhook "validation.awscluster.infrastructure.cluster.x-k8s.io" denied the request: AWSCluster.infrastructure.cluster.x-k8s.io "test-cluster" is invalid: spec.additionalTags: Invalid value: "My Value": value cannot have characters other than alphabets, numbers, spaces and _ . : / = + - @ .
```

https://go.dev/play/p/I3ZAkuVY7aY

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
