### ISSUE TITLE
Configuration of the EC2 metadata endpoint 

### ISSUE THREAD

**Issue by AljoschaP** [kubernetes-sigs/cluster-api-provider-aws#3744]
/kind feature

**Describe the solution you'd like**
As a user I would like to configure a specific metadata version on each EC2 instance started by CAPI and/or disable the metadata endpoint completely. I would prefer to use the AWSMachineTemplate to disable/enable the metadata endpoint, set the metadata version (e.g. IMDSv2) and set the HttpPutResponseHopLimit.

For example:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: test
spec:
  template:
    spec:
     httpEndpointEnabled: true // true or false allowed
     httpTokens: required // required (v2) or optional (v1 or v2) allowed
     httpPutResponseHopLimit: 1 //1-64 allowed
```

**Anything else you would like to add:**

IMDSv2 is the second version of the instance metadata service and it uses a session-based approach while v1 uses a request/response method. Because its a [security issue](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/) to use v1 instead of v2 the AWS Securityhub reports it with a severity of HIGH.

-  AWS supports it via the EC2 console/AWS CLI for new instances and via the [AWS CLI](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-metadata-options.html) for running instances. 
- Terraform supports it via the [Metadata Options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options) field.

**Environment:**

- Cluster-api-provider-aws version: 1.5.0
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): Amazon Linux 2
