### ISSUE TITLE
Label on AWSMachinePool

### ISSUE THREAD

**Issue by cablunar** [kubernetes-sigs/cluster-api-provider-aws#3828]
/kind feature

**Describe the solution you'd like**
A label object on the AWSMachinePool, that can be configured in the spec for each of the AWSMachinePools that you run in your cluster. This label, will translate to labels on the kubernetes node obejcts in the cluster.

Goal: `kubectl get nodes -L mylabel | grep something`

Example config:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachinePool
metadata:
  name: aws-cluster-nodes
  namespace: aws-cluster
spec:
  minSize: 3
  maxSize: 6
  labels:
  - "kubernets.io/role=node"
  - "machinepool=aws-cluster-nodes"
  - "mylabel=something"
  availabilityZones:
  - us-east-1
  awsLaunchTemplate:
    ...
```

**Anything else you would like to add:**
This is just a suggestion of how it could be configured.
Open for suggestions on how to configure it in another way.
