### ISSUE TITLE
EKSConfigTemplate specs not being reflected in the bootstrap script

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/cluster-api-provider-aws#3848]
/kind bug

**What steps did you take and what happened:**
Launched an EKS cluster with the provided template adding two specs namely `useMaxPods` and `kubeletExtraArgs` in the EKSConfigTemplate CRD and providing ref of this CRD in the MachinePool CRD.

These values didn't get reflected in the bootstrap script.

**What did you expect to happen:**
Expected these values to be reflected in the bootstrap script.

**Anything else you would like to add:**
The template I used:

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capa-eks-test
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: capa-eks-test-control-plane
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: capa-eks-test-control-plane
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: capa-eks-test-control-plane
  namespace: default
spec:
  region: us-west-1
  sshKeyName: default
  version: v1.22.9
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: capa-eks-test-pool-0
  namespace: default
spec:
  clusterName: capa-eks-test
  replicas: 3
  template:
    spec:
      bootstrap:
        configRef:
          name: capa-eks-test-eks-config-template
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: EKSConfigTemplate
      clusterName: capa-eks-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSManagedMachinePool
        name: capa-eks-test-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSManagedMachinePool
metadata:
  name: capa-eks-test-pool-0
  namespace: default
spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: EKSConfigTemplate
metadata:
  name: capa-eks-test-eks-config-template
spec:
  template:
    spec:
      kubeletExtraArgs:
        log-flush-frequency: 10s
      useMaxPods: true

```
The bootstrap script generated:
`/etc/eks/bootstrap.sh default_capa-eks-test-control-plane --kubelet-extra-args '--node-labels=eks.amazonaws.com/nodegroup-image=ami-0007a810a3e61783c,eks.amazonaws.com/capacityType=ON_DEMAND,eks.amazonaws.com/nodegroup=default_capa-eks-test-pool-0 --max-pods=17' --b64-cluster-ca $B64_CLUSTER_CA --apiserver-endpoint $API_SERVER_URL --dns-cluster-ip $K8S_CLUSTER_DNS_IP --use-max-pods false
`
**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
