### ISSUE TITLE
capa failes to reconcile  `boilerplate-oidc-trust-policy` if status.ARN is present

### ISSUE THREAD

**Issue by sadysnaat** [kubernetes-sigs/cluster-api-provider-aws#3851]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Tried creating an EKS cluster with AssociateOIDCProvider
if capa fails to create boilerplate-oidc-trust-policy in target env 

```bash
E1114 10:34:30.128276       1 controller.go:326]  "msg"="Reconciler error" "error"="failed to reconcile control plane for AWSManagedControlPlane cluster-xxx/xxx-cp: failed reconciling OIDC provider for cluster: failed to reconcile trust policy in workload cluster: getting client for remote cluster: Get \"https://xxxxxx.xxx.us-east-1.eks.amazonaws.com/api?timeout=10s\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" "aWSManagedControlPlane"={"name":"xxx-cp","namespace":"cluster-xxx"} "controller"="awsmanagedcontrolplane" "controllerGroup"="controlplane.cluster.x-k8s.io" "controllerKind"="AWSManagedControlPlane" "name"="xxx-cp" "namespace"="cluster-xxx" "reconcileID"="46a5a30e-6920-4f67-8cc2-ad32a3b16237"
```

it sets 

```yaml
  oidcProvider:
    arn: arn:aws:iam::xxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/xxx
    trustPolicy: '{  "Version": "2012-10-17",  "Statement": [    {      "Principal":
      {        "Federated": [          "arn:aws:iam::xxx:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/xxx"        ]      },      "Effect":
      "Allow",      "Action": [        "sts:AssumeRoleWithWebIdentity"      ],      "Condition":
      {        "ForAnyValue:StringLike": {          "oidc.eks.us-east-1.amazonaws.com/id/xxx:sub":
      [            "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME}"          ]        }      }    }  ]}'
  ready: true
```

but doesn't create `boilerplate-oidc-trust-policy` in next reconcile loops as
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/8dca96840be545ec6a01822be2bd24755ba6262e/pkg/cloud/services/eks/oidc.go#L46

**What did you expect to happen:**
I expected in next reconcile loops this `boilerplate-oidc-trust-policy` to be created

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 1.5.9
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`): linux
