### ISSUE TITLE
AWSLaunchTemplate spec missing in the AWSManagedMachinePool crd yaml.

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/cluster-api-provider-aws#3852]
/kind bug

**What steps did you take and what happened:**
I was trying to launch an eks cluster with a custom ami. Added the awsLaunchTemplate spec in the AWSManagedMachinePool crd and got this error:
`error: error validating "cluster-template-eks.yaml": error validating data: ValidationError(AWSManagedMachinePool.spec): unknown field "awsLaunchTemplate" in io.x-k8s.cluster.infrastructure.v1beta1.AWSManagedMachinePool.spec; if you choose to ignore these errors, turn validation off with --validate=false`

On further debugging I noticed that the AWSManagedMachinePool's Go definition contains this spec but the crd's yaml(provided below) doesn't.

**What did you expect to happen:**
I expected the cluster launch to happen without any error.

**Anything else you would like to add:**
AWSManagedMachinePool crd's yaml:
```
spec:
            description: AWSManagedMachinePoolSpec defines the desired state of AWSManagedMachinePool
            properties:
              additionalTags:
                additionalProperties:
                  type: string
                description: AdditionalTags is an optional set of tags to add to AWS
                  resources managed by the AWS provider, in addition to the ones added
                  by default.
                type: object
              amiType:
                default: AL2_x86_64
                description: AMIType defines the AMI type
                enum:
                - AL2_x86_64
                - AL2_x86_64_GPU
                - AL2_ARM_64
                type: string
              amiVersion:
                description: AMIVersion defines the desired AMI release version. If
                  no version number is supplied then the latest version for the Kubernetes
                  version will be used
                minLength: 2
                type: string
              availabilityZones:
                description: AvailabilityZones is an array of availability zones instances
                  can run in
                items:
                  type: string
                type: array
              diskSize:
                description: DiskSize specifies the root disk size
                format: int32
                type: integer
              eksNodegroupName:
                description: EKSNodegroupName specifies the name of the nodegroup
                  in AWS corresponding to this MachinePool. If you don't specify a
                  name then a default name will be created based on the namespace
                  and name of the managed machine pool.
                type: string
              instanceType:
                description: InstanceType specifies the AWS instance type
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Labels specifies labels for the Kubernetes node objects
                type: object
              providerIDList:
                description: ProviderIDList are the provider IDs of instances in the
                  autoscaling group corresponding to the nodegroup represented by
                  this machine pool
                items:
                  type: string
                type: array
              remoteAccess:
                description: RemoteAccess specifies how machines can be accessed remotely
                properties:
                  public:
                    description: Public specifies whether to open port 22 to the public
                      internet
                    type: boolean
                  sourceSecurityGroups:
                    description: SourceSecurityGroups specifies which security groups
                      are allowed access
                    items:
                      type: string
                    type: array
                  sshKeyName:
                    description: SSHKeyName specifies which EC2 SSH key can be used
                      to access machines. If left empty, the key from the control
                      plane is used.
                    type: string
                type: object
              roleName:
                description: RoleName specifies the name of IAM role for the node
                  group. If the role is pre-existing we will treat it as unmanaged
                  and not delete it on deletion. If the EKSEnableIAM feature flag
                  is true and no name is supplied then a role is created.
                type: string
              scaling:
                description: Scaling specifies scaling for the ASG behind this pool
                properties:
                  maxSize:
                    format: int32
                    type: integer
                  minSize:
                    format: int32
                    type: integer
                type: object
              subnetIDs:
                description: SubnetIDs specifies which subnets are used for the auto
                  scaling group of this nodegroup
                items:
                  type: string
                type: array
            type: object
```

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
