### ISSUE TITLE
metrics port is not exposed properly in default configuration 

### ISSUE THREAD

**Issue by faiq** [kubernetes-sigs/cluster-api-provider-aws#3856]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
- While trying to debug a cluster I was trying to look up controller runtime metrics. However, when I got onto my prometheus dashboard I wasn't able to see any metrics that pertained to the `cluster-api` controller pod. 
- Upon further investigation it looks like the port :8080 is not exposed via a container port and the service that comes in the infrastructure-components.yaml doesn't expose that either in the `ports` section of the manager container

**What did you expect to happen:**
- metrics should be scraped automatically if a service monitor is created for it

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
To make this work i had to make the following changes

i added the following container port to the manager container 
```
        - containerPort: 8080
          protocol: TCP
``` 

I changed metrics bind address to the following

```
        - --metrics-bind-addr=0.0.0.0:8080
```

finally i added a new service so my service monitor could scrape it 

```
apiVersion: v1
kind: Service
metadata:
  name: capa-metrics
  namespace: capa-system
spec:
  selector:
    cluster.x-k8s.io/provider: infrastructure-aws
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
```

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
