### ISSUE TITLE
Upgrade to v2 with self managed vpc breaks at ipv6 validation

### ISSUE THREAD

**Issue by project0** [kubernetes-sigs/cluster-api-provider-aws#3912]
/kind bug

**What steps did you take and what happened:**
We just upgraded our cluster from  v1.5.2 to v2.0.2 and experience a issue with a cluster control plane what has a custom vpc attached to it (The cluster api managed vpc control planes looks fine and do not have this issue).

Basically the validation webhook refuses to update the object and assumes it will suddenly change to ipv6 (true), what is actually not the case as the `ipv6` attribute is not set: `Invalid value: true: changing IP family is not allowed after it has been set"`

**What did you expect to happen:**
No error :-)

**Anything else you would like to add:**

```
E1205 14:44:30.761837       1 controller.go:326] 
"Reconciler error" err="failed to reconcile network for AWSManagedControlPlane flux-system/cluster-cp: failed to patch unmanaged VPC fields: admission webhook \"validation.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io\" denied the request: 
AWSManagedControlPlane.controlplane.cluster.x-k8s.io \"cluster-cp\" is invalid: 
spec.networkSpec.vpc.enableIPv6: Invalid value: true: changing IP family is not allowed after it has been set" 
controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" aWSManagedControlPlane="flux-system/cluster-cp" namespace="flux-system" name="cluster-cp" reconcileID=9e543f17-7d08-4f40-946b-564c62c0d60b
```

the AWSManagedControlPlane has the following vpc config, ipv6 is not set at all.
```yaml
    vpc:
      availabilityZoneSelection: Ordered
      availabilityZoneUsageLimit: 3
      cidrBlock: 10.0.0.0/16
      id: vpc-071369d4254b8964e
      tags:
        Cluster: vpc-shared
        Name: vpc-shared
```
Note: The vpc itself has ipv6 enabled, maybe it is inherited from the default subnet config?

**Environment:**
- capi: 1.2.6
- Cluster-api-provider-aws version: 2.0.1
- Kubernetes version: (use `kubectl version`): 1.24.7
- OS (e.g. from `/etc/os-release`): amazon linux EKS
