### ISSUE TITLE
Node SecurityGroup suddenly re-created in wrong VPC

### ISSUE THREAD

**Issue by project0** [kubernetes-sigs/cluster-api-provider-aws#3943]
/kind bug

**What steps did you take and what happened:**
At some point in the night we lost all machines of a cluster as CAPA did seem to create a new security group in the wrong VPC (with the same name) and updated the managed controlplane resource with it. We ended up with two SG with the same name, but in different VPC. Apparently CAPA choose the wrong and instances could not be launched anymore.  

I guess this is also important: The cluster is deployed in CAPA managed VPC mode, but we have a separate self managed VPC in the same region, what has the appropriate cluster tags for the same clustername on the subnets. However, this VPC is currently not used at all as we had some problems and switched back to CAPA managed VPC. Maybe the controller got confused here?

**What did you expect to happen:**
Never create resources outside of the assigned VPC and subnets?

**Anything else you would like to add:**
I cannot find anything useful in the logs, just that the instances got removed because of failed state by AWS, after that everything started failing

> 2022-12-21T05:08:48Z	 >
2022-12-21T05:08:48Z			status code: 400, request id: 08539fc5-f5f7-48f4-af23-f86c509e8129
2022-12-21T05:08:48Z		failed to modify network interfaces on instance "i-0b090788e23ea71a9": failed to modify interface "eni-0b18009f9c7bdb312" to have security groups [sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]: InvalidGroup.NotFound: You have specified two resources that belong to different networks.
2022-12-21T05:08:48Z	E1221 05:08:48.578139       1 logger.go:84] "unable to ensure security groups" err=<
2022-12-21T05:08:48Z	I1221 05:08:48.344608       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-98tsv" namespace="flux-system" name="s00-euw2-eks-hub-479483661-98tsv" reconcileID=8e99d398-7567-41c0-aa61-a1e49d6b1fd2 machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-dqbp6" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:48Z	I1221 05:08:48.223686       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-vcz8v" namespace="flux-system" name="s00-euw2-eks-hub-479483661-vcz8v" reconcileID=22791f63-2f78-42af-9f3c-2d91cf7a794c machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-lhj8t" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:47Z	E1221 05:08:47.712016       1 logger.go:84] "unable to ensure security groups" err=<
2022-12-21T05:08:47Z	I1221 05:08:47.393184       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-vcz8v" namespace="flux-system" name="s00-euw2-eks-hub-479483661-vcz8v" reconcileID=e3e7856d-e8bb-47af-b42b-0cbb0d6f1fec machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-lhj8t" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:47Z	I1221 05:08:47.389013       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-98tsv" namespace="flux-system" name="s00-euw2-eks-hub-479483661-98tsv" reconcileID=29010eb2-6e2d-445e-b3d4-bb72bd37999d machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-dqbp6" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:46Z		failed to modify network interfaces on instance "i-0ef1f0e31b6416b0c": failed to modify interface "eni-0f3ff10723b14b4b5" to have security groups [sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]: InvalidGroup.NotFound: You have specified two resources that belong to different networks.
2022-12-21T05:08:46Z	E1221 05:08:46.824221       1 controller.go:326] "Reconciler error" err=<
2022-12-21T05:08:46Z	I1221 05:08:46.643521       1 logger.go:68] "Handling deleted AWSMachine"
2022-12-21T05:08:46Z	I1221 05:08:46.598881       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.518858       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-vcz8v" namespace="flux-system" name="s00-euw2-eks-hub-479483661-vcz8v" reconcileID=d9b6c869-cbf2-4272-97b4-e8e5cdd93b63 machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-lhj8t" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:46Z	I1221 05:08:46.507458       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.461575       1 logger.go:68] "Updating security groups" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" aWSMachine="flux-system/s00-euw2-eks-hub-479483661-98tsv" namespace="flux-system" name="s00-euw2-eks-hub-479483661-98tsv" reconcileID=52c71ef4-cd3c-4b44-810a-07b2199691ce machine="flux-system/s00-euw2-eks-hub-eu-west-2a-md0-7fcff79dd7-dqbp6" cluster="flux-system/s00-euw2-eks-hub" groups=[sg-067d344bca229711a sg-01e82c63bd0f70ef2 sg-0004a0aabd408f5e8]
2022-12-21T05:08:46Z	I1221 05:08:46.317598       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.283620       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.242595       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.162139       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.139567       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.119522       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.068455       1 logger.go:68] "Error state detected, skipping reconciliation"
2022-12-21T05:08:46Z	I1221 05:08:46.024412       1 logger.go:68] "Unexpected EC2 instance termination" state=terminated instance-id="i-0e8b99ebe671326f2"
2022-12-21T05:08:46Z	I1221 05:08:46.024375       1 logger.go:68] "EC2 instance state changed" state=terminated instance-id="i-0e8b99ebe671326f2"

wrong state: 
```yaml
      vpc:
        availabilityZoneSelection: Ordered
        availabilityZoneUsageLimit: 3
        cidrBlock: 10.1.0.0/20
        id: vpc-08c953887b746ec04
        internetGatewayId: igw-0298f0d8d51617c55
        tags:
          Cluster: s00-euw2-eks-hub
          Name: s00-euw2-eks-hub-vpc
          sigs.k8s.io/cluster-api-provider-aws/cluster/s00-euw2-eks-hub: owned
          sigs.k8s.io/cluster-api-provider-aws/role: common
    networkStatus:
      securityGroups:
        cluster:
          id: sg-01e82c63bd0f70ef2
          name: eks-cluster-sg-s00-euw2-eks-hub-338615027
          tags:
            Name: eks-cluster-sg-s00-euw2-eks-hub-338615027
            aws:eks:cluster-name: s00-euw2-eks-hub
            kubernetes.io/cluster/s00-euw2-eks-hub: owned
        node:
          id: sg-0004a0aabd408f5e8
          name: eks-cluster-sg-s00-euw2-eks-hub-338615027
          tags:
            Name: eks-cluster-sg-s00-euw2-eks-hub-338615027
            aws:eks:cluster-name: s00-euw2-eks-hub
            kubernetes.io/cluster/s00-euw2-eks-hub: owned
        node-eks-additional:
          id: sg-067d344bca229711a
          name: s00-euw2-eks-hub-node-eks-additional
          tags:
            Cluster: s00-euw2-eks-hub
            Name: s00-euw2-eks-hub-node-eks-additional
            sigs.k8s.io/cluster-api-provider-aws/cluster/s00-euw2-eks-hub: owned
            sigs.k8s.io/cluster-api-provider-aws/role: node-eks-additional
```

**Environment:**

- Cluster-api-provider-aws version: 2.0.2
- Kubernetes version: (use `kubectl version`): 1.24.7
- OS (e.g. from `/etc/os-release`): amazon linux 2 eks
