### ISSUE TITLE
AdditionalTags webhook validation issue?

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/cluster-api-provider-aws#3975]
/kind bug

**What steps did you take and what happened:**
I am attempting to provision a cluster where the AWS instances have the following tag set:
```
custodian_downtime: "Offhours tz=et"
```

Here is an example AWSMachine:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachine
metadata:
  name: tag-test
  namespace: default
spec:
  additionalTags:
    custodian_downtime: Offhours tz=et
  cloudInit:
    insecureSkipSecretsManager: true
  instanceType: m5a.2xlarge
  rootVolume:
    encrypted: true
    size: 200
    type: gp2
  sshKeyName: ""
```

Attempting to apply this AWSMachine gives the result:
```
The AWSMachine "tag-test" is invalid: spec.additionalTags: Invalid value: "Offhours tz=et": value cannot have characters other than alphabets, numbers, spaces and _ . : / = + - @ .
```

**What did you expect to happen:**
The AWSMachine should be applied as the tag value passes the validation (according to the output message).

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-aws version: v1.5.1
- Kubernetes version: (use `kubectl version`): v1.21.9
- OS (e.g. from `/etc/os-release`):
