### ISSUE TITLE
Externally provisioned egresses get removed upon cluster deletion

### ISSUE THREAD

**Issue by pierreyves-lebrun** [kubernetes-sigs/cluster-api-provider-aws#3986]
/kind bug

**What steps did you take and what happened:**
Created cluster with the following spec:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: test
spec:
  controlPlaneLoadBalancer:
    crossZoneLoadBalancing: true
    scheme: "internal"
  region: some-region
  network:
    vpc:
      id: some-id
    subnets:
      - id: some-id
      - id: some-id
      - id: some-id
```

Cluster creation happened as expected, but upon deletion all egresses attached to the specified VPC get deleted.

**What did you expect to happen:**

I would expect that all egresses predating cluster creation remain upon cluster deletion.

**Anything else you would like to add:**
I believe the following code is at fault:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/egress_only_gateways.go#L79-L107

Before raising a pull request, I'd like to confirm what is the intended behavior of the above function.

**Environment:**

- Cluster-api-provider-aws version: 2.0.2 
- Kubernetes version: 1.23.14
