### ISSUE TITLE
User-provided `Name` tag on subnets get overwritten

### ISSUE THREAD

**Issue by AverageMarcus** [kubernetes-sigs/cluster-api-provider-aws#3989]
/kind bug

**What steps did you take and what happened:**

Specify a subnet on an `AWSCluster` CR that has a `Name` tag defined. E.g. 

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: example
spec:
  network:
    subnets:
    - availabilityZone: eu-north-1a
      cidrBlock: 10.0.0.0/24
      isPublic: false
      tags:
        Name: example-custom-subnet-name
```

This `Name` tag will be instead replaced with one built in code and instead become `Name: example-subnet-private-eu-north-1a`

**What did you expect to happen:**

If a `Name` tag is provided by the user it is what should be used when creating / updating the subnet. If not provided CAPA should default to the current generated format.

**Anything else you would like to add:**

Block of code building the Name value: https://github.com/giantswarm/cluster-api-provider-aws/blob/70373384dc117ea387d28a8548d49ecc58e7cca0/pkg/cloud/services/network/subnets.go#L426-L441

Block of code overwriting any user-provided Name tag: https://github.com/giantswarm/cluster-api-provider-aws/blob/70373384dc117ea387d28a8548d49ecc58e7cca0/api/v1beta1/tags.go#L198-L200

As far as I can see, that tag isn't used anywhere in the codebase for matching or looking up of subnets. It seem purely for display.

Multiple subnets can end up with the same Name value.

**Environment:**

- Cluster-api-provider-aws version: >= 1.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
