### ISSUE TITLE
Lifecycle Hooks for MachinePool/ASG

### ISSUE THREAD

**Issue by sebltm** [kubernetes-sigs/cluster-api-provider-aws#4020]
/kind feature

**Describe the solution you'd like**
ASGs have support for Lifecycle Hooks and it's a good idea to expose this in the MachinePool CRD. When I scale up and down my ASGs, I want to be able to execute some Lambda functions to create and delete other resources that my nodes need. Doing this through the lifecycle hook allows me to only allow the creation of the EC2 instance to go ahead if the Lambda function ran successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): v1.26.0
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04

**Comment by dlipovetsky** [comment]
@sebltm I think you mean the `AWSMachinePool` CRD.

Please describe how the hooks work with ASGs. Where do the hooks get defined in the ASG API? Do they have to be implemented using AWS Lambda? What changes to IAM policies would be required? Thanks!

/triage needs-information

**Comment by Ankitasw** [comment]
@dlipovetsky Here are some links regarding lifecycle hooks:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/lifecycle-hooks.html
https://docs.aws.amazon.com/autoscaling/ec2/userguide/adding-lifecycle-hooks.html#adding-lifecycle-hooks-aws-cli

**Comment by sebltm** [comment]
Sorry I’d forgotten about this one! The hooks can target SNS, SQS or EventBridge - whether there’s also a Lambda or something else shouldn’t be part of the scope of this implementation. Rather should be led to the user to implement in my opinion.
We should just add a ``lifecycleHook`` with the ARN of the resource they’ve decided to use:
```yaml
lifecycleHook:
  sns:
  sqs:
  eventBridge:
```
(Only one of the options above should be mentioned)

**Comment by sebltm** [comment]
Hi, can we reopen this issue I'd like to take a look at it

**Comment by sebltm** [comment]
@dlipovetsky 
The lifecycle hooks need to be created after the ASG. I propose adding the AWSMachinePool and AWSManagedMachinePool CRDs a field:

```yaml
lifecycleHooks:
- name: <name of the lifecycle hook; required>
  notificationTargetARN: <ARN of a target like an SQS or SNS queue otherwise the default is EventBridge; optional>
  roleARN: <role ARN to use for the hook; optional>
  lifecycleTransition: <the instance state to which to attach the hook; required>
  heartbeatTimeout: <the timeout in seconds associated to the hook after which the default action is used, default is 3600 seconds; optional>
  defaultResult: <action taken after timeout, either CONTINUE or ABANDON, default is ABANDON; optional>
  notificationMetadata: <some additional string data passed to the target; optional>
```

which would be reconciled after the ASG is created and deleted after the ASG is deleted.
The management of the target (EventBridge, SQS and SNS) is out of the scope of this controller and should be managed by a thirdparty system
