### ISSUE TITLE
Support for node selectors and taints with MachinePools

### ISSUE THREAD

**Issue by rudimk** [kubernetes-sigs/cluster-api-provider-aws#4043]
/kind feature

**Describe the solution you'd like**

I'm looking at a scenario where an `EKSConfig` object can contain node selectors and taints, that I'd like to apply to a `MachinePool`'s nodes. So perhaps something along these lines:

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: EKSConfig
metadata:
  name: eks-mp-1-mp-1
  namespace: default
spec:
  kubeletExtraArgs:
    node-labels: "rudimk.com/workload-kind=system"
    register-with-taints: "rudimk.com/workload-kind=system:NoSchedule"
```

From what I can gather, it seems simple enough to modify https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/bootstrap/eks/internal/userdata/kubelet_args.go, and add support for the `--node-labels` and `--register-with-taints` flags. I was wondering - is there a broader/deeper architectural reason why the provider doesn't have these flags - especially since the entire `spec` for an `EKSConfig` object can be left blank by default? If not, would love to raise a PR in the next couple days for this. 

**Anything else you would like to add:**

NA

**Environment:**

- Cluster-api-provider-aws version: v2.0.2
- Kubernetes version: (use `kubectl version`): K3s 1.24.10(CAPI controller) | EKS 1.24.9(CAPI-provisioned cluster)
- OS (e.g. from `/etc/os-release`): macOS 12.5
