### ISSUE TITLE
AWSMachineTemplate validation webhook is not configured, and its unit tests are broken

### ISSUE THREAD

**Issue by cnmcavoy** [kubernetes-sigs/cluster-api-provider-aws#4116]
/kind bug

**What steps did you take and what happened:**
The AWSMachineTemplate validation webhook is not configured as expected, and so it is never used at runtime. In addition, because the configuration is missing, envtest fails to hit the code path for validation and unit tests for the AWSMachineTemplate webhook effectively never run. Also, when you restore the missing configuration, the tests are broken and fail to pass.

**What did you expect to happen:**
The AWSMachineTemplate validation webhook should be configured for the capa controller manager and the tests should pass.

**Anything else you would like to add:**

The missing webhook configuration should be inserted here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/config/webhook/manifests.yaml#L410 and the correct config is:
```
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta2-awsmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachinetemplate.infrastructure.cluster.x-k8s.io
  rules:
    - apiGroups:
        - infrastructure.cluster.x-k8s.io
      apiVersions:
        - v1beta2
      operations:
        - CREATE
        - UPDATE
      resources:
        - awsmachinetemplates
  sideEffects: None
  ```

**Environment:** N/A
