### ISSUE TITLE
:bug: Users are able to submit bad data to healthCheckProtocol 

### ISSUE THREAD

**Issue by faiq** [kubernetes-sigs/cluster-api-provider-aws#4182]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

I created an AWSCluster Object 

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  finalizers:
  - awscluster.infrastructure.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/cluster-name: faiq-test
  name: faiq-test
  namespace: default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Cluster
    name: faiq-test
spec:
  bastion:
    allowedCIDRBlocks:
    - 0.0.0.0/0
    enabled: false
  controlPlaneEndpoint:
    host: <redacted>
    port: 6443
  controlPlaneLoadBalancer:
    crossZoneLoadBalancing: false
    healthCheckProtocol: HTTPS:6443/healthz
    scheme: internet-facing
  identityRef:
```

specifying `spec.controlPlaneLoadBalancer.healthCheckProtocol: HTTPS:6443/healthz`.

I expect this to fail in the validating webhooks because only [allow specifying the protocol](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/5538c89bdfe245afa76bd9b72c0f64c92a865325/pkg/cloud/services/elb/loadbalancer.go#L943)

The fix here would be in the validating webhook. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
