### ISSUE TITLE
Support Govcloud & China Partitions

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#4216]
/kind feature
/help
/triage accepted
/priority important-longterm

**Describe the solution you'd like**
We should be able to support using CAPA in other AWS partitions such as Govcloud and China. Currently, we still assume the `aws` partition in our code in certain places. For example:

- https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c42dc926cdb75cba82558d71a0341951a19cc085/pkg/cloud/services/eks/roles.go#L42
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c42dc926cdb75cba82558d71a0341951a19cc085/pkg/cloud/services/s3/s3.go#L245

**clusterawsadm** allows you to change the partition via a confile file:

```yaml
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSIAMConfiguration
spec:
  partition: aws-us-gov
```

**Anything else you would like to add:**

This is about going through the code and ensuring that we don't assume the **aws** partition. From the controller manager, we should be able to get the partition from the creds of the user.

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
