### ISSUE TITLE
Custom AMI freezes initialisation of cluster

### ISSUE THREAD

**Issue by d3btech** [kubernetes-sigs/cluster-api-provider-aws#4414]
When `AWSMachineTemplate` is provided with a custom `ami`, even those available through `clusterawsadm` the cluster creation freezes at `WaitingForKubeadmInit`

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
....
spec:
  template:
    spec:
      ami:
        id: ami-0c6f34a64f2ba7ea6
      instanceType: t3.medium
      ....
```

EDIT:

Just checked with all the prebuilt images and nothing is working except the `Ubuntu` images. For all other `AMI` the initialisation freezes.

```
❯ clusterawsadm ami list --kubernetes-version v1.27.3 --region us-west-2
KUBERNETES VERSION   REGION      OS               NAME                                         AMI ID
v1.27.3              us-west-2   centos-7         capa-ami-centos-7-v1.27.3-1686976915         ami-007ab2508f82e52b9
v1.27.3              us-west-2   ubuntu-18.04     capa-ami-ubuntu-18.04-v1.27.3-1686976912     ami-0b2b8b55f63f7d59a
v1.27.3              us-west-2   ubuntu-20.04     capa-ami-ubuntu-20.04-v1.27.3-1686976883     ami-02434261db642b2c8
v1.27.3              us-west-2   amazon-2         capa-ami-amazon-2-v1.27.3-1686976919         ami-0c6f34a64f2ba7ea6
v1.27.3              us-west-2   flatcar-stable   capa-ami-flatcar-stable-v1.27.3-1686976923   ami-0d1c474f8eea8a9d1
```
