### ISSUE TITLE
Instance failing to get register with ControlPlane Load Balancer

### ISSUE THREAD

**Issue by jainpulkit22** [kubernetes-sigs/cluster-api-provider-aws#4499]
/kind bug

**What steps did you take and what happened:**
When I applied the cluster yaml, controlPlaneLoadBalancer was successfully created, and also the controlplane instance was created but the control plane instance was not getting registered with the apiserver load balancer, there it showed some instance AZ issue. But when I registered the instance manually with the load balancer fro the aws console the registration succeded.
[A clear and concise description of what the bug is.]

**What did you expect to happen:**
It should have been registered itself without manual intervention.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
I am not using direct AWS_ACCESS_KEY and AWS_SECRET_ACCESS_KEY rather i have an iam role specified and with the help of the provided credentials i am assuming the specified role.

Error log:
```
E0912 14:54:28.596219       1 logger.go:83] "failed to reconcile LB attachment" err="could not register control plane instance \"i-***\" with classic load balancer: failed to register instance with APIServer ELB \"***\": instance is in availability zone \"\", no public subnets attached to the ELB in the same zone"
E0912 14:54:28.596760       1 controller.go:329] "Reconciler error" err="could not register control plane instance \"i-*****\" with classic load balancer: failed to register instance with APIServer ELB \"*****\": instance is in availability zone \"\", no public subnets attached to the ELB in the same zone" controller="awsmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="AWSMachine" AWSMachine="matrix--k8s-v1-25-1-build-num-109/matrix--k8s-v1-25-1-build-num-109-control-plane-jthxg" namespace="matrix--k8s-v1-25-1-build-num-109" name="matrix--k8s-v1-25-1-build-num-109-control-plane-jthxg" reconcileID="ace428f4-4dc8-4c17-9f2c-8cc1741e6f3c"
```

One more question is that why is the availability zone of instance is displayed as \"\".

**Environment:**

- Cluster-api-provider-aws version:  v2.2
- Kubernetes version: (use `kubectl version`): v1.25.1 
- OS (e.g. from `/etc/os-release`):  ubuntu

**Comment by jainpulkit22** [comment]
@vincepri can you have a look at it

**Comment by jainpulkit22** [comment]
@adammw can you provide assistance on this.

**Comment by adammw** [comment]
sounds more like a support/troubleshooting question.

do you have a copy of the cluster yaml applied?

does the controller have access to check the region/availability zone with your role? [docs](https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html?highlight=load#control-plane-load-balancer) mention CAPI should choose private over public subnets if you have both

**Comment by jainpulkit22** [comment]
> sounds more like a support/troubleshooting question.
> 
> do you have a copy of the cluster yaml applied?
> 
> does the controller have access to check the region/availability zone with your role? [docs](https://cluster-api-aws.sigs.k8s.io/topics/bring-your-own-aws-infrastructure.html?highlight=load#control-plane-load-balancer) mention CAPI should choose private over public subnets if you have both

yes
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: CLUSTERNAME
    jenkins-test: 
  name: CLUSTERNAME
  namespace: CLUSTERNAMESPACE
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: CLUSTERNAME-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AWSCluster
    name: CLUSTERNAME
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: CLUSTERNAME
  namespace: CLUSTERNAMESPACE
spec:
  region: us-west-2
  sshKeyName: SSHAUTHORIZEDKEYS
  network: 
    vpc: 
      id: VPCID
    subnets:
    - id: SUBNETID
    securityGroupOverrides:
      node: NODESG
      controlplane: CONTROLPLANESG
  controlPlaneLoadBalancer:
    scheme: internal
    healthCheckProtocol: TCP
    subnets: [SUBNETID]
    additionalSecurityGroups: [CONTROLPLANESG]
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: CLUSTERNAME-control-plane
  namespace: CLUSTERNAMESPACE
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: aws
      controllerManager:
        extraArgs:
          cloud-provider: aws
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: aws
        name: '{{ ds.meta_data.local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AWSMachineTemplate
      name: CLUSTERNAME-control-plane
  replicas: 1
  version: K8SVERSION
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: CLUSTERNAME-control-plane
  namespace: CLUSTERNAMESPACE
spec:
  template:
    spec:
      subnet:
        id: SUBNETID
      publicIP: false
      ami:
        id: AMIID
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.xlarge
      sshKeyName: SSHAUTHORIZEDKEYS
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: CLUSTERNAME
  name: CLUSTERNAME-md-0
  namespace: CLUSTERNAMESPACE
spec:
  clusterName: CLUSTERNAME
  replicas: 2
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: CLUSTERNAME
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: CLUSTERNAME-md-0
      clusterName: CLUSTERNAME
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: CLUSTERNAME-md-0
      version: K8SVERSION
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: CLUSTERNAME-md-0
  namespace: CLUSTERNAMESPACE
spec:
  template:
    spec:
      subnet:
        id: SUBNETID
      publicIP: false
      ami:
        id: AMIID
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t2.xlarge
      sshKeyName: SSHAUTHORIZEDKEYS
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: CLUSTERNAME-md-0
  namespace: CLUSTERNAMESPACE
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: aws
          name: '{{ ds.meta_data.local_hostname }}
```
