### ISSUE TITLE
All control plan created in one az for self maintained Load Balancer 

### ISSUE THREAD

**Issue by archerwu9425** [kubernetes-sigs/cluster-api-provider-aws#4633]
/kind bug

**What steps did you take and what happened:**
I'm trying to create a aws cluster by cluster-aws. For the network(VPC, subnet) and control-plane NLB all created by terraform and self maintained.  The `AWSCluster` is like below:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: {{ .Values.infra_api.name }}
  labels:
    cnp_cluster: {{ .Values.infra_api.name }}
  annotations:
    controlplane.cluster.x-k8s.io/skip-kube-proxy: ""
spec:
  region: {{ .Values.infra_api.aws_infra_region }}
  identityRef:
    kind: AWSClusterStaticIdentity
    name: xxxx-identity
  controlPlaneLoadBalancer:
    name:  xxxx-apiserver-prv
    scheme: internal
    loadBalancerType: nlb
  sshKeyName: ""

  network:
    vpc:
      id: xxxxx
    subnets:
    - id: xxxx
    - id: xxxx
    - id: xxxx
```

I have set 3 azs, but when I deploy the cluster-api resources with 3 control-planes, all control-planes exist in one az.

**What did you expect to happen:**
The 3 control-plane should be created in the 3 azs, each az with one control-palne

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: v2.1.1
- Kubernetes version: (use `kubectl version`): 1.23.10
- OS (e.g. from `/etc/os-release`):
