### ISSUE TITLE
Control plane node replacement causes kube-apiserver access issues due to delayed AWSMachine deletion

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes-sigs/cluster-api-provider-aws#4697]
/kind bug

**What steps did you take and what happened:**
During a rolling update of a KCP, I noticed that the instance was deregistered at the load balancer (NLB) as soon as the AWSMachine was deleted.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/2a790d41db929d9ffaac8d7db7d64462ac27989e/controllers/awsmachine_controller.go#L330-L332
However, there was a timeframe of about 3 minutes between CAPI Machine deletion (because of the node drain) and CAPA AWSMachine deletion, which caused the kube-apiserver access to be faulty during this timeframe.

tl;dr of what's happening:

- 🆗 scale down of a control plane
- 🆗 CAPI deletes the control plane Machine
- 🆗 the etcd member of the node will be removed immediately
- ⚡ kube-apiserver requests are broken to this control plane
- ⚡all Pods will be drained from the control plane
- ⚡ as soon as all Pods are drained CAPI will delete the InfraMachine (i.e., AWSMachine)
- 🆗 the AWSMachine controller deregisters the instance from the LB

One additional issue I can see is: as the kube-apiserver request via the LB is partially broken *all* nodes will become `NotReady` and will remove their endpoints to all Service load balancers after a while. Because of this all load balancers are inaccessible during a control plane rollout. This should never happen IMO.

**What did you expect to happen:**

I expected the AWSMachine to be deleted immediately after the CAPI Machine was deleted, so that the kube-apiserver access would not be affected. I expected the deletion process to be seamless and not cause any disruptions to my cluster.
But maybe this is something we cannot handle in CAPA but more like in CAPI.

**Anything else you would like to add:**

We have mitigated the issue by using a custom controller that watches on the `pre-drain.delete.hook.machine.cluster.x-k8s.io` hook for control plane machines and deletes the corresponding AWSMachine. AFAIK the deletion of the AWSMachine will not wait for all Pods to be drained. But this is okay in our clusters as there are only our controllers and exporters running on the control plane nodes.

**Environment:**

- Cluster-api-provider-aws version: 2.0.3 (w/o using CC)
- Kubernetes version: v1.26.10
- OS: Ubuntu

<sub>Tobias Giese <tobias.giese@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by AndiDog** [comment]
/triage accepted
/priority important-soon

I believe I've also seen a few times that Kubernetes API access wasn't consistently available during control plane node replacement. Easy to observe with tools like `k9s` or just `watch kubectl get [...]`.

**Comment by tobiasgiese** [comment]
An example AWSCluster from us:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: my-fancy-cluster
  name: my-fancy-cluster
  namespace: my-fancy-cluster
spec:
  bastion:
    enabled: false
  controlPlaneLoadBalancer:
    crossZoneLoadBalancing: true
    loadBalancerType: nlb
    preserveClientIP: true
    scheme: internal
    subnets:
      - subnet-xxx
```

But it seems to be a generic issue, not only related to NLBs. I just mentioned that we are using NLB to be specific in the issue description.
