### ISSUE TITLE
Not Removing Previous Roles and Users within iamAuthenticatorConfig

### ISSUE THREAD

**Issue by wcrum** [kubernetes-sigs/cluster-api-provider-aws#4740]
/kind bug

**What steps did you take and what happened:**
Updating `iamAuthenticatorConfig` with multiple roles or users, then removing roles does not remove old roles and users, only appends new arns.

1. Define CAPA `iamAuthenticatorConfig`.
```
iamAuthenticatorConfig:
  mapUsers:
  - groups:
    - system:masters
    userarn: arn:aws:iam::111122223333:user/my-user
    username: my-user
  - groups:
    - system:masters
    userarn: arn:aws:iam::111122223333:user/my-second-user
    username: my-second-user
```
2. Define `iamAuthenticatorConfig` removing a user.
```
iamAuthenticatorConfig:
  mapUsers:
  - groups:
    - system:masters
    userarn: arn:aws:iam::111122223333:user/my-second-user
    username: my-second-user
```
3. Result within `kube-system/aws-auth`.
```
   mapUsers: |                                                                                                                                                                            
     - groups:                                                                                                                                                                           
       - system:masters                                                                                                                                                                   
       userarn: arn:aws:iam::111122223333:user/my-user                                                                                                                                     
       username: my-user
     - groups:                                                                                                                                                                           
       - system:masters                                                                                                                                                                   
       userarn: arn:aws:iam::111122223333:user/my-second-user                                                                                                                                 
       username: my-second-user
```

**What did you expect to happen:**
The expected behavior is to have `kube-system/aws-auth` to only have the defined users / roles.
```
   mapUsers: |                                                                                                                                                                            
     - groups:                                                                                                                                                                           
       - system:masters                                                                                                                                                                   
       userarn: arn:aws:iam::111122223333:user/my-second-user                                                                                                                                 
       username: my-second-user
```

**Anything else you would like to add:**
Would like to clarify if this is expected or unexpected behavior. Not removing users / roles could be a security risk.

**Environment:**

- Cluster-api-provider-aws version: v2.3.1
- Kubernetes version: (use `kubectl version`): v1.28.4
- OS (e.g. from `/etc/os-release`): macOS 14.1.1 (23B81)
