### ISSUE TITLE
Unable to create fargate profile

### ISSUE THREAD

**Issue by murali-krishna** [kubernetes-sigs/cluster-api-provider-aws#4807]
/kind bug

**What steps did you take and what happened:**
I'm trying to create an eks cluster with fargate profile using [this template](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/templates/cluster-template-eks-fargate.yaml)

EKS cluster creation works fine. However, fargate profile throws an error stating:
```
Internal error occurred: failed calling webhook "default.awsfargateprofile.infrastructure.cluster.x-k8s.io": failed to call webhook: the server could not find the requested resource
```
All capi & capa pods are running fine in the management cluster.

```
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "cluster-foo"
spec:
  infrastructureRef:
    kind: AWSManagedCluster
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    name: "cluster-foo"
  controlPlaneRef:
    kind: AWSManagedControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    name: "cluster-foo-control-plane"
---
kind: AWSManagedCluster
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
metadata:
  name: "cluster-foo"
spec: {}
---
kind: AWSManagedControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
metadata:
  name: "cluster-foo-control-plane"
spec:
  network:
    vpc:
      id: vpc-foo
    subnets:
    - id: subnet-1
    - id: subnet-2
    - id: subnet-3
  region: "ap-southeast-2"
  version: "1.29"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSFargateProfile
metadata:
  name: "cluster-foo-fargate-0"
spec:
  clusterName: "cluster-foo"
  selectors:
    - namespace: default
```

**Environment:**

- Cluster-api-provider-aws version: v2.3.1
- Kubernetes version: (use `kubectl version`): 1.26
