### ISSUE TITLE
Support installing "latest" EKS addon

### ISSUE THREAD

**Issue by richardcase** [kubernetes-sigs/cluster-api-provider-aws#5184]
/kind feature

**Describe the solution you'd like**

Currently when you specify EKS addons to be installed in `AWSManagedControlPlane` you need to specify the specific version of the addon. It would also be good to support installing the latest supported version of the addon.

So currently you need to do:

```yaml
  spec:
    addons:
    - conflictResolution: overwrite
      name: vpc-cni
      version: v1.18.1-eksbuild.3
```

But it would also be nice to support the following:

```yaml
  spec:
    addons:
    - conflictResolution: overwrite
      name: vpc-cni
      version: latest
```

If `latest` is specified then we need to query for the latest supported version for the cluster/k8s version (using `DescribeAddonVersions`) and use that.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
