### ISSUE TITLE
AWSManagedMachinePool cannot instantiate CUSTOM ami

### ISSUE THREAD

**Issue by emanuele-leopardi** [kubernetes-sigs/cluster-api-provider-aws#5457]
Hello there!

First of all, thanks for this fantastic piece of software.

I'm encountering an issue with AWSManagedMachinePool.

I was able to create a Pool with the following code 
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: eks-management-cluster-pool-0
spec:
  availabilityZones:
    - eu-south-1a
    - eu-south-1b
    - eu-south-1c
  amiType: AL2_ARM_64
  instanceType: t4g.nano
  diskSize:  10
  capacityType: spot
  scaling: 
    minSize: 2
    maxSize: 2
```
and I can see the Pool in the console + in k8s 

![Image](https://github.com/user-attachments/assets/9d7d77c6-0296-4447-ad46-063d6d965d88)

Unfortunately as you can see from the image above I am not able to span up a secondary pool with the following code
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: eks-management-cluster-pool-1
spec:
  amiType: "CUSTOM"
  availabilityZones:
    - eu-south-1a
    - eu-south-1b
    - eu-south-1c
  awsLaunchTemplate:
    ami:
      id : ami-0eaaf34f5f7090cb4 #bottlerocket
    instanceType: c5.large
    name: ema-test
  scaling:
    maxSize: 1
    minSize: 1
```

What I'm trying to achieve is having a Pool using and AMI for Bottlerocket 

I've found an [Issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4708) where @cnmcavoy  and @praveenadini

where at least able to create a pool and make workers joining the cluster. So I'm probably doing something wrong or missing some code to achieve it. 

Can anyone please shed some light on this matter?
