### ISSUE TITLE
Machine does not have a corresponding Node yet (Machine.status.nodeRef not set)

### ISSUE THREAD

**Issue by abrekhov** [kubernetes-sigs/cluster-api-provider-aws#5503]
/kind bug

**What steps did you take and what happened:**
i applied the manifests

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: aws-micro-kube-identity
  namespace: aws-micro-kube
spec:
  allowedNamespaces:
    list:
      - aws-micro-kube
  secretRef: aws-credentials
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSCluster
metadata:
  name: aws-micro-kube
  namespace: aws-micro-kube
spec:
  region: eu-central-1
  sshKeyName: aws-micro-kube-ssh
  identityRef:
    kind: AWSClusterStaticIdentity
    name: aws-micro-kube-identity
  controlPlaneLoadBalancer:
    loadBalancerType: nlb
    scheme: internal
  network:
    vpc:
      id: vpc-hashhh
      availabilityZoneUsageLimit: 2
      availabilityZoneSelection: Random
    subnets:
      - id: subnet-hashhhh
        availabilityZone: eu-central-1a
        isPublic: false
      - id: subnet-hashhh
        availabilityZone: eu-central-1b
        isPublic: false
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: aws-micro-kube-control-plane
  namespace: aws-micro-kube
spec:
  template:
    spec:
      instanceType: m6i.xlarge
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: aws-micro-kube-ssh
      cloudInit:
        insecureSkipSecretsManager: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSMachineTemplate
metadata:
  name: aws-micro-kube-md-0
  namespace: aws-micro-kube
spec:
  template:
    spec:
      instanceType: c7i.8xlarge
      iamInstanceProfile: "nodes.cluster-api-provider-aws.sigs.k8s.io"
      sshKeyName: aws-micro-kube-ssh
      cloudInit:
        insecureSkipSecretsManager: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: aws-micro-kube-control-plane
  namespace: aws-micro-kube
spec:
  replicas: 3
  version: v1.30.8 # to fetch available by default clusterawsadm ami list
  rolloutBefore:
    certificatesExpiryDays: 364  # Trigger rollout if certificates expire within 21 days
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: aws-micro-kube-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname.split(".")[0] }}'
    joinConfiguration:
      nodeRegistration:
        name: '{{ ds.meta_data.local_hostname.split(".")[0] }}'
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: aws-micro-kube-md-0
  namespace: aws-micro-kube
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: '{{ ds.meta_data.local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aws-micro-kube
  namespace: aws-micro-kube
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: aws-micro-kube-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSCluster
    name: aws-micro-kube
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: aws-micro-kube-md-0
  namespace: aws-micro-kube
spec:
  clusterName: aws-micro-kube
  replicas: 6
  selector:
    matchLabels:
      cluster.x-k8s.io/deployment-name: aws-micro-kube-md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/deployment-name: aws-micro-kube-md-0
    spec:
      clusterName: aws-micro-kube
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: aws-micro-kube-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSMachineTemplate
        name: aws-micro-kube-md-0
      version: v1.30.8
    
```

- One control plane node is up ✅ 
- Worker nodes is up ✅ 
- internal NLB is up ✅ 
- But it cannot scale to 3 control plane node ⚠ 

**What did you expect to happen:**
KubeadmControlProvider should spin 3 ec2 for master.

**Anything else you would like to add:**
capi logs:

```
I0522 23:13:52.868524       1 controller.go:362] "Reconcile KubeadmControlPlane" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="aws-micro-kube/aws-micro-kube-control-plane" namespace="aws-micro-kube" name="aws-micro-kube-control-plane" reconcileID="b5ad5be2-b9f4-4507-9059-9266cc6299cb" Cluster="aws-micro-kube/aws-micro-kube"
I0522 23:13:52.871736       1 controller.go:490] "Scaling up control plane" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="aws-micro-kube/aws-micro-kube-control-plane" namespace="aws-micro-kube" name="aws-micro-kube-control-plane" reconcileID="b5ad5be2-b9f4-4507-9059-9266cc6299cb" Cluster="aws-micro-kube/aws-micro-kube" desired=3 existing=1
I0522 23:13:52.871771       1 scale.go:257] "Waiting for control plane to pass preflight checks" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="aws-micro-kube/aws-micro-kube-control-plane" namespace="aws-micro-kube" name="aws-micro-kube-control-plane" reconcileID="b5ad5be2-b9f4-4507-9059-9266cc6299cb" Cluster="aws-micro-kube/aws-micro-kube" failures="Machine aws-micro-kube-control-plane-gfdfw does not have a corresponding Node yet (Machine.status.nodeRef not set)"
I0522 23:13:52.871897       1 recorder.go:104] "Waiting for control plane to pass preflight checks to continue reconciliation: Machine aws-micro-kube-control-plane-gfdfw does not have a corresponding Node yet (Machine.status.nodeRef not set)" logger="events" type="Warning" object={"kind":"KubeadmControlPlane","namespace":"aws-micro-kube","name":"aws-micro-kube-control-plane","uid":"dff770f8-c317-40c0-b2c9-83dfc007c1a8","apiVersion":"controlplane.cluster.x-k8s.io/v1beta1","resourceVersion":"9620958336"} reason="ControlPlaneUnhealthy"
```

```
kgno
NAME                       STATUS   ROLES           AGE   VERSION
ip-10-255-51-123   Ready    <none>          8h    v1.30.8
ip-10-255-51-191           Ready    control-plane   8h    v1.30.8
ip-10-255-51-200   Ready    <none>          8h    v1.30.8
ip-10-255-51-220   Ready    <none>          8h    v1.30.8
ip-10-255-51-247   Ready    <none>          8h    v1.30.8
ip-10-255-51-67    Ready    <none>          8h    v1.30.8
ip-10-255-51-93    Ready    <none>          8h    v1.30.8
```

**Environment:**

- Cluster-api-provider-aws version: v2.8.2
- Kubernetes version: (use `kubectl version`): 1.30.8
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04.2 LTS

**Comment by alex-kuprin** [comment]
I got exactly same issue with vultr provider. I expect 3 control planes. 2 of them are actually working and in state ready.
But 2nd control plane machine is in Provisioned state, not Running. 1st Control plane is running.

I've already installed CNI, CCM and CSI in the cluster. Pods in provisioned cluster are running. But KubeadmControlProvider not scaling up to 3 nodes 


```
NAME                                                         CLUSTER         NODENAME                            PROVIDERID                                     PHASE         AGE   VERSION
machine.cluster.x-k8s.io/test-main-ams-control-plane-d2djf   test-main-ams                                       vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f   Provisioned   16m   v1.32.4
machine.cluster.x-k8s.io/test-main-ams-control-plane-kk9ns   test-main-ams   test-main-ams-control-plane-kk9ns   vultr://0e579f76-a0ac-4ced-b4d3-c733232793b9   Running       21m   v1.32.4
```

```
I0626 22:39:12.340511       1 controller.go:490] "Scaling up control plane" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="default/test-main-ams-control-plane" namespace="default" name="test-main-ams-control-plane" reconcileID="0a6bb5fd-e09b-416f-a8b4-59d1e8bcc4df" Cluster="default/test-main-ams" desired=3 existing=2
I0626 22:39:12.340723       1 scale.go:257] "Waiting for control plane to pass preflight checks" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="default/test-main-ams-control-plane" namespace="default" name="test-main-ams-control-plane" reconcileID="0a6bb5fd-e09b-416f-a8b4-59d1e8bcc4df" Cluster="default/test-main-ams" failures="Machine test-main-ams-control-plane-d2djf does not have a corresponding Node yet (Machine.status.nodeRef not set)"
I0626 22:39:12.340831       1 recorder.go:104] "Waiting for control plane to pass preflight checks to continue reconciliation: Machine test-main-ams-control-plane-d2djf does not have a corresponding Node yet (Machine.status.nodeRef not set)" logger="events" type="Warning" object={"kind":"KubeadmControlPlane","namespace":"default","name":"test-main-ams-control-plane","uid":"de834b85-00e6-469f-98ba-c2743f853a47","apiVersion":"controlplane.cluster.x-k8s.io/v1beta1","resourceVersion":"6195"} reason="ControlPlaneUnhealthy"
```

**Comment by alex-kuprin** [comment]
When I describe machine that is still in Provisioning state
`kubectl describe machine.cluster.x-k8s.io/test-main-ams-control-plane-d2djf`

I got this output:
```
Name:         test-main-ams-control-plane-d2djf
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=test-main-ams
              cluster.x-k8s.io/control-plane=
              cluster.x-k8s.io/control-plane-name=test-main-ams-control-plane
Annotations:  controlplane.cluster.x-k8s.io/kubeadm-cluster-configuration:
                {"etcd":{},"networking":{},"apiServer":{},"controllerManager":{"extraArgs":{"enable-hostpath-provisioner":"true"}},"scheduler":{},"dns":{}...
              pre-terminate.delete.hook.machine.cluster.x-k8s.io/kcp-cleanup: 
API Version:  cluster.x-k8s.io/v1beta1
Kind:         Machine
Metadata:
  Creation Timestamp:  2025-06-26T22:23:49Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generation:  3
  Owner References:
    API Version:           controlplane.cluster.x-k8s.io/v1beta1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  KubeadmControlPlane
    Name:                  test-main-ams-control-plane
    UID:                   de834b85-00e6-469f-98ba-c2743f853a47
  Resource Version:        4623
  UID:                     df2321e1-0a32-41c0-bf40-2d391a3a0bce
Spec:
  Bootstrap:
    Config Ref:
      API Version:     bootstrap.cluster.x-k8s.io/v1beta1
      Kind:            KubeadmConfig
      Name:            test-main-ams-control-plane-d2djf
      Namespace:       default
      UID:             7d324b53-0560-4ff0-8d55-38db85cb7a8f
    Data Secret Name:  test-main-ams-control-plane-d2djf
  Cluster Name:        test-main-ams
  Infrastructure Ref:
    API Version:          infrastructure.cluster.x-k8s.io/v1beta1
    Kind:                 VultrMachine
    Name:                 test-main-ams-control-plane-d2djf
    Namespace:            default
    UID:                  f4ceb720-7215-473b-9886-5ca57335ea19
  Node Deletion Timeout:  10s
  Provider ID:            vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f
  Readiness Gates:
    Condition Type:  APIServerPodHealthy
    Condition Type:  ControllerManagerPodHealthy
    Condition Type:  SchedulerPodHealthy
    Condition Type:  EtcdPodHealthy
    Condition Type:  EtcdMemberHealthy
  Version:           v1.32.4
Status:
  Addresses:
    Address:        10.7.96.5
    Type:           InternalIP
    Address:        95.179.139.41
    Type:           ExternalIP
  Bootstrap Ready:  true
  Conditions:
    Last Transition Time:  2025-06-26T22:24:17Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2025-06-26T22:23:50Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2025-06-26T22:24:17Z
    Status:                True
    Type:                  InfrastructureReady
    Last Transition Time:  2025-06-26T22:24:17Z
    Message:               Waiting for a node with matching ProviderID to exist
    Reason:                NodeProvisioning
    Severity:              Warning
    Status:                False
    Type:                  NodeHealthy
  Infrastructure Ready:    true
  Last Updated:            2025-06-26T22:24:17Z
  Observed Generation:     3
  Phase:                   Provisioned
  v1beta2:
    Conditions:
      Last Transition Time:  2025-06-26T22:23:49Z
      Message:               
      Observed Generation:   3
      Reason:                NotReady
      Status:                False
      Type:                  Available
      Last Transition Time:  2025-06-26T22:24:17Z
      Message:               * NodeHealthy: Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
* Control plane components: Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
* EtcdMemberHealthy: Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                ReadyUnknown
      Status:                Unknown
      Type:                  Ready
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               
      Observed Generation:   3
      Reason:                UpToDate
      Status:                True
      Type:                  UpToDate
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               
      Observed Generation:   3
      Reason:                Ready
      Status:                True
      Type:                  BootstrapConfigReady
      Last Transition Time:  2025-06-26T22:24:17Z
      Message:               
      Observed Generation:   3
      Reason:                Ready
      Status:                True
      Type:                  InfrastructureReady
      Last Transition Time:  2025-06-26T22:23:49Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  NodeHealthy
      Last Transition Time:  2025-06-26T22:23:49Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  NodeReady
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  EtcdPodHealthy
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  EtcdMemberHealthy
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  APIServerPodHealthy
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  ControllerManagerPodHealthy
      Last Transition Time:  2025-06-26T22:23:50Z
      Message:               Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist
      Observed Generation:   3
      Reason:                InspectionFailed
      Status:                Unknown
      Type:                  SchedulerPodHealthy
      Last Transition Time:  2025-06-26T22:23:49Z
      Message:               
      Observed Generation:   3
      Reason:                NotPaused
      Status:                False
      Type:                  Paused
      Last Transition Time:  2025-06-26T22:23:49Z
      Message:               
      Observed Generation:   3
      Reason:                NotDeleting
      Status:                False
      Type:                  Deleting
Events:                      <none>
```

From the output you can see that machine Spec.Provider ID is set to vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f

But error message is "Waiting for a Node with spec.providerID vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f to exist"
What is wrong with a node?

**Comment by alex-kuprin** [comment]
Finally I'v found out that provisioned new nodes are not getting spec.providerID
I've tryed to manually patch node (in provisioned cluster) by this command:
`kubectl patch node test-main-ams-control-plane-d2djf -p '{"spec":{"providerID":"vultr://8ad636bf-aac0-44ec-9aba-2dbc5ce0ec0f"}}'`

And it scaled up to 3 nodes. But 3rd node again has no spec.providerID.

Where should I look to find why spec.providerID was not assigned to provisioned node?
Should it be CCM or cluster api provider?

**Comment by alex-kuprin** [comment]
@abrekhov 

Finally I found out that problem is solved by setting to KubeadmControlPlane 'cloud-provider: external'

```yaml
clusterConfiguration:
  apiServer:
    extraArgs:
      cloud-provider: external
  controllerManager:
    extraArgs:
      cloud-provider: external
initConfiguration:
  nodeRegistration:
    kubeletExtraArgs:
      cloud-provider: external
joinConfiguration:
  nodeRegistration:
    kubeletExtraArgs:
      cloud-provider: external
```

If it is not set CCM is not requested for providerID. After setting 'cloud-provider: external' all new nodes get marked with providerID.

**It is not cluster API issue**

**Comment by aviral-agarwal** [comment]
Hey

I am getting the same issue and I am trying out with default manifests generated using 
`clusterctl generate cluster`

following is the default `KubeadmControlPlane`, already w/  `cloud-provider: external`

```
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: capi-quickstart-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: "{{ ds.meta_data.local_hostname }}"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
        name: "{{ ds.meta_data.local_hostname }}"
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
      kind: AWSMachineTemplate
      name: capi-quickstart-control-plane
  replicas: 3
  version: v1.32.0
```

This one is not working for me
Any support is appreciated
