### ISSUE TITLE
Cannot use AL2023 with EKS 1.33 and AWS Launch Template

### ISSUE THREAD

**Issue by afarbos** [kubernetes-sigs/cluster-api-provider-aws#5530]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I deployed an AWS Managed Machine Pool and tried to specify and AWS launch template with `amiType: AL2023_x86_64_STANDARD` on EKS 1.33.
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name:  eks-pool0
  namespace: capa
spec:
  eksNodegroupName: pool0
  scaling:
    minSize: 1
    maxSize: 2
  amiType: AL2023_x86_64_STANDARD
  awsLaunchTemplate:
    instanceType: m7i.4xlarge
    instanceMetadataOptions:
      httpPutResponseHopLimit: 2
``` 
I got the following error:
```
Failed to reconcile launch template:
failed to get ami SSM parameter:
"/aws/service/eks/optimized-ami/1.33/amazon-linux-2/recommended/image_id": ParameterNotFound:`
```

**What did you expect to happen:**

No error

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

These values seems hardcoded here https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/ec2/ami.go#L80-L87 and called from https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/ec2/ami.go#L328

**Environment:**

- Cluster-api-provider-aws version: 2.8.2
- Kubernetes version: (use `kubectl version`): 1.33
- OS (e.g. from `/etc/os-release`):
