### ISSUE TITLE
Taints not propagated correctly to node object

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#793]
/kind bug

**What steps did you take and what happened:**
I want to pass in taints inside of a machine deployment. This is how I defined machine deployment:

```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: tt523
  namespace: b46ee553b2cc9ff639498178c1dddae0e28c9930
  labels:
    cluster.k8s.io/cluster-name: m3333
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.k8s.io/cluster-name: m3333
      set: node
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: m3333
        set: node
    spec:
      taints:
      - effect: NoSchedule
        key: taintKey
        value: taintValue
      versions:
        kubelet: v1.14.0
      providerSpec:
        value:
          ...
```

It created the machine deployment and when I run kubectl describe machinedeployment I can see that the taint is part of the machine deployment:
```
Spec:
...
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        Cluster . K 8 S . Io / Cluster - Name:  m3333
        Set:                                    node
    Spec:
      Metadata:
        Creation Timestamp:  <nil>
      Provider Spec:
        Value:
          API Version:           awsprovider/v1alpha1
          Iam Instance Profile:  nodes.cluster-api-provider-aws.sigs.k8s.io
          Instance Type:         m5.large
          Key Name:              gophoton-global-keypair
          Kind:                  AWSMachineProviderSpec
      Taints:
        Effect:  NoSchedule
        Key:     taintKey
        Value:   taintValue
      Versions:
        Kubelet:  v1.14.0
Status:
  Observed Generation:   2
  Replicas:              1
  Unavailable Replicas:  1
  Updated Replicas:      1
```

However, When I actually run kubectl describe node, the node object doesn't contain the taint:
```
kubectl --kubeconfig=provisionedcon.yaml describe node ip-10-0-0-25.us-west-2.compute.internal
Name:               ip-10-0-0-25.us-west-2.compute.internal
...
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.0.0.25/24
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 23 May 2019 16:13:35 -0700
Taints:             <none>
Unschedulable:      false
Conditions:
```

**What did you expect to happen:**
When I do kubectl describe node, I can see the taint in the node object.

**Anything else you would like to add:**
I have also tried putting taints under "template.taints" and it doesn't populate to the machine or machine deployment object. It needs to be under template.spec.taints.

**Environment:**

- Cluster-api-provider-aws version: 
    Image:         gcr.io/cluster-api-provider-aws/cluster-api-aws-controller:v0.2.1
    Image ID:      docker-pullable://gcr.io/cluster-api-provider-aws/cluster-api-aws-controller@sha256:0c2807ce459a090ccd92ca0c89f35ac47fb6e839ce61ff9216c8bd1ce7957e21

- Kubernetes version: (use `kubectl version`): 1.14.0
- OS (e.g. from `/etc/os-release`):  CAPA running on photon OS
