### ISSUE TITLE
Support laying down arbitrary files on disk

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#847]
/kind feature

**Describe the solution you'd like**
Some Kubernetes API server features require additional configuration files.
Add support to the API to be able to lay down these files prior to kubeadm initialization.
cloud-init has a files section that can be utilised to achieve this, but will need to be wary of exceeding the 16KB userdata limit (see #846)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
Possibly related to #838

**Comment by ncdc** [comment]
We may want to move this to the kubeadm bootstrapper as part of v1alpha2

**Comment by ncdc** [comment]
Looking at one CAPV userdata example, it's at around 10kb compressed. That doesn't leave a ton of room for a CA pem, a client cert pem, and a client cert key (use case: support kube-apiserver webhook token authentication). What other mechanisms are worth considering, if we hit the userdata limit on certain providers?

**Comment by randomvariable** [comment]
I guess either SSM Parameter Store or S3.m

@bryanl had some concerns around using SSM Parameter Store stability.

SSM or S3 will require additional IAM configuration. S3 will also need a globally unique bucket for a customer, and would need explicit configuration in the CRDs, so makes UX a bit trickier. Did originally test using SSM in #189, which did work at the time.

**Comment by detiber** [comment]
Some initial brainstorming on options:
- If we start installing the agent, we could use AWS systems manager to inject data
  - We currently don't require ssh access and I think this is a better and more auditable way to do the interaction
- downloading from a remote location, such as Naadir suggested.

**Comment by vincepri** [comment]
+1 for SSM

**Comment by randomvariable** [comment]
We don't need the SSM agent to inject data. It's a terribly named product - it's actually a suite of 10 different things. Think of Parameter Store as a per-region K/V store just for EC2

**Comment by detiber** [comment]
The SSM agent probably wouldn't be a horrible thing to add, as it would open the ability to run remote commands later.

**Comment by randomvariable** [comment]
Yup. Removing the bastion instances also cleans up the cluster controller too.

**Comment by ncdc** [comment]
I am curious how we might express this in an API that is consistent across different infrastructure providers, and how we would implement it.

**Comment by vincepri** [comment]
Does it have to be agnostic/generic? For v1alpha2 we can have the infrastructure provider to best decide what to do with the Bootstrap.Data field. Maybe we can add more to the kubeadm provider specification so the data isn't unstructured.

**Comment by ncdc** [comment]
If we go that route, we'd probably want to spec out a standard set of use cases, field names, etc. to provide a firm handshake between the output of a bootstrap provider and an infra provider using it for pre-boot setup.

**Comment by detiber** [comment]
I don't think we should try to prematurely abstract away an interface for this, I'm +1 for just spec'ing out the use cases and behaviors we expect for v1alpha2.

**Comment by randomvariable** [comment]
Think these are the native options, excluding some more esoteric ones like AWS Cloud Directory.
| Type                | Advantages                                                                                                                                                                                                                                  | Disadvantages                                                                                                                                                                                                                          |
| ------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| SSM Parameter Store | <ul><li>No data store addressing requirements.</li><li>Support prefix-based ACLs</li><li>Transparent encryption via KMS</li><ul>                                                                                                            | <ul><li>4KB and 8KB limit for values (standard and advanced parameters)                                                                                                                                                                |
| DynamoDB            | <ul><li>1MB records</li><li>Can support arbitrary fields</li><li>Tables do not need to be globally unique, so can standardise on "cluster-api-provider-aws-sigs-k8s-io" or similar<li>Now supports transparent encryption via KMS</li></ul> | <ul><li>Table needs provisioning</li><li>Complex IAM permissioning</li>                                                                                                                                                                |
| AWS S3              | <ul><li>Allows for arbitrary file limits</li><li>De facto standardised protocol, so could be used by other providers via object storage<li>Transparent encryption supported</li><ul>                                                        | <ul><li>User must set up bucket, globally unique across all customers</li><li>S3 bucket configuration becomes another field to configure on the CRDs</li><li>Very flexible IAM permissions makes it easy to misconfigure and leak</li> |

**Comment by moshloop** [comment]
Another cross-platform option would be Github Secret gists, or just plain Git + Deploy Keys

**Comment by moshloop** [comment]
> Possibly related to #838

Yes - this is the exact use case konfigadm was designed for

**Comment by chuckha** [comment]
What kind of files are we talking about? I'd like to see a list of what we want to support before we go too far down any implementation path. 

@randomvariable where did this request come from? Which kube-apiserver feature(s) did people want to use?

**Comment by moshloop** [comment]
My use cases include environment and systemd files for running a consul agent and api-server client-side load balancer.

There might also be other use-cases that a daemonset is not always suitable for e.g. SSH CA certificates, custom networking, remote logging/auditing, MOTD/Issue files, vault tokens

**Comment by ncdc** [comment]
@chuckha one use case is being able to configure webhook token authentication, which requires setting apiserver flags, writing files to disk (ca pem, client cert pem, client cert key) that ultimately need to be placed inside the kube-apiserver container. If we do find a way to write the certs to the server, do we have a way for kubeadm to get them into the kube-apiserver pod?

**Comment by randomvariable** [comment]
@chuckha right now anything to do with security, access and authorization. So these will be YAML files, which will technically be typed, so that would be another way to support them (though a huge vendoring annoyance), and PKI material. Those are the only ones I've seen that we specifically need.

Some examples:
- Additional static pod manifests for API server encryption providers
- Static admission control configuration ( apiserver.k8s.io/v1alpha1/AdmissionConfiguration ), configuired via `-admission-control-config-file` extraArg.
- `eventratelimit.admission.k8s.io/v1alpha1/Configuration` file, passed in as a document in the file provided to `-admission-control-config-file` extraArg.
- PEM file for a plethora of other flags such as  `--oidc-ca-file`

There's a case to be made that as has been done for auditing, more of these configurations should be reimplemented as dynamic.

As for getting these into the pod, this should be configurable via the `extraVolumes` property of `apiServer` in `kubeadm.k8s.io/v1beta1/ClusterConfiguration` onwards, e.g.
```
--- yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServer:
  timeoutForControlPlane: 4m0s
  certSANs:
  - redacted
  extraArgs:
    audit-dynamic-configuration: "true"
#    anonymous-auth: "false" # Not supported yet
    profiling: "false"
    runtime-config: "auditregistration.k8s.io/v1alpha1=true"
    audit-log-path: /var/log/kubernetes/audit.log
    audit-log-maxsize: "256"
    audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
    audit-log-maxbackup: "5"
    encryption-provider-config: /etc/kubernetes/encryption-provider-config.yaml
    admission-control-config-file: /etc/kubernetes/admission-control-config.yaml
    enable-admission-plugins: EventRateLimit,AlwaysPullImages,PodSecurityPolicy,ResourceQuota,NodeRestriction,OwnerReferencesPermissionEnforcement,PersistentVolumeClaimResize,PodTolerationRestriction,StorageObjectInUseProtection
    service-account-signing-key-file: "/etc/kubernetes/pki/sa.key"
  extraVolumes:
  - name: "kmsplugin"
    hostPath: "/var/run/kmsplugin"
    mountPath: "/var/run/kmsplugin"
    readOnly: false
    pathType: DirectoryOrCreate
  - name: "encryption-provider"
    hostPath: "/etc/kubernetes/encryption-provider-config.yaml"
    mountPath: "/etc/kubernetes/encryption-provider-config.yaml"
    readOnly: true
    pathType: FileOrCreate
  - name: "audit-policy"
    hostPath: "/etc/kubernetes/audit-policy.yaml"
    mountPath: "/etc/kubernetes/audit-policy.yaml"
    readOnly: true
    pathType: FileOrCreate
  - name: "admission-control-config"
    hostPath: "/etc/kubernetes/admission-control-config.yaml"
    mountPath: "/etc/kubernetes/admission-control-config.yaml"
    readOnly: true
    pathType: FileOrCreate
  - name: "event-rate-limit"
    hostPath: "/etc/kubernetes/event-rate-limit.yaml"
    mountPath: "/etc/kubernetes/event-rate-limit.yaml"
    readOnly: true
    pathType: FileOrCreate
  - name: "log"
    hostPath: "/var/log/kubernetes"
    mountPath: "/var/log/kubernetes"
    readOnly: false
    pathType: DirectoryOrCreate
```
