### ISSUE TITLE
ha cluster:  subnet reconcile miss to check and create route table

### ISSUE THREAD

**Issue by Sn0rt** [kubernetes-sigs/cluster-api-provider-aws#967]
/kind bug

I want to create ha cluster with three node and the three located in different AZ.

I try the POC as follow step:

1: set the ENV
2: generate the yaml of cluster
3: apply the Cluster YAML to managerCluster
4: create two subnetes and get the subnet id // this is by manually
5: modify the control-plane machine to set the subnet ID
6: apply the the control-plane MachineList 

but, now the route table NOT contain the NAT route with the two subnet which create by hand. 

the subnet list as follow 

```json
{
    "Subnets": [
        {
            "AvailabilityZone": "us-east-2b",
            "AvailabilityZoneId": "use2-az2",
            "AvailableIpAddressCount": 250,
            "CidrBlock": "10.0.2.0/24",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-0c870838a83e8819e",
            "VpcId": "vpc-080002927c8fd2b02",
            "OwnerId": "179516646050",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "ha01-subnet-private"
                },
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/cluster/ha01",
                    "Value": "owned"
                },
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/role",
                    "Value": "private"
                }
            ],
            "SubnetArn": "arn:aws:ec2:us-east-2:179516646050:subnet/subnet-0c870838a83e8819e"
        },
        {
            "AvailabilityZone": "us-east-2c",
            "AvailabilityZoneId": "use2-az3",
            "AvailableIpAddressCount": 250,
            "CidrBlock": "10.0.3.0/24",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-0b393a067c067a4e7",
            "VpcId": "vpc-080002927c8fd2b02",
            "OwnerId": "179516646050",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/role",
                    "Value": "private"
                },
                {
                    "Key": "Name",
                    "Value": "ha01-subnet-private"
                },
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/cluster/ha01",
                    "Value": "owned"
                }
            ],
            "SubnetArn": "arn:aws:ec2:us-east-2:179516646050:subnet/subnet-0b393a067c067a4e7"
        },
        {
            "AvailabilityZone": "us-east-2a",
            "AvailabilityZoneId": "use2-az1",
            "AvailableIpAddressCount": 250,
            "CidrBlock": "10.0.0.0/24",
            "DefaultForAz": false,
            "MapPublicIpOnLaunch": false,
            "State": "available",
            "SubnetId": "subnet-00113a5f5e0d762f9",
            "VpcId": "vpc-080002927c8fd2b02",
            "OwnerId": "179516646050",
            "AssignIpv6AddressOnCreation": false,
            "Ipv6CidrBlockAssociationSet": [],
            "Tags": [
                {
                    "Key": "Name",
                    "Value": "ha01-subnet-private"
                },
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/cluster/ha01",
                    "Value": "owned"
                },
                {
                    "Key": "sigs.k8s.io/cluster-api-provider-aws/role",
                    "Value": "private"
                }
            ],
            "SubnetArn": "arn:aws:ec2:us-east-2:179516646050:subnet/subnet-00113a5f5e0d762f9"
        }
    ]
}
```

**Comment by ncdc** [comment]
@detiber what is our stance on this - if you create your own subnet, should you also have to manually complete the rest of the steps, or should CAPA take care of configuring the route table correctly, even with manually created subnets?

**Comment by detiber** [comment]
@ncdc I'm against trying to configure the route tables, since we would not know the intentions of the user providing an existing subnet. Do they intend to use a NAT gateway or handle routing a different way? If so, which NAT gateway if there are multiple?

**Comment by ncdc** [comment]
@detiber that's how I'm leaning as well. Just so I'm clear - @Sn0rt did you let CAPA create everything **except** for the subnets? i.e. did CAPA create the route table?

**Comment by Sn0rt** [comment]
> @detiber that's how I'm leaning as well. Just so I'm clear - @Sn0rt did you let CAPA create everything **except** for the subnets? i.e. did CAPA create the route table?

in fact, I want use CAPA to create every things such as subnet, and its route table. 

however, I am not found a useful guide to tell me how to create a HA cluster with whole region.

I just found a example yaml from `creating-multinode-controlplane-clusters.md`  file.

```yaml
kind: Machine
metadata:
    name: aws-controlplane-0
    labels:
        cluster.k8s.io/cluster-name: <CLUSTER_NAME>
        set: controlplane
spec:
    versions:
        kubelet: v1.13.3
        controlPlane: v1.13.3
    providerSpec:
        value:
            apiVersion: awsprovider/v1alpha1
            kind: AWSMachineProviderSpec
            instanceType: "t2.medium"
            iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
            keyName: "laptop"
            subnet:
                id: <SUBNET_IN_AZ1_ID>
---
kind: Machine
metadata:
    name: aws-controlplane-1
    labels:
        cluster.k8s.io/cluster-name: <CLUSTER_NAME>
        set: controlplane
spec:
    versions:
        kubelet: v1.13.3
        controlPlane: v1.13.3
    providerSpec:
        value:
            apiVersion: awsprovider/v1alpha1
            kind: AWSMachineProviderSpec
            instanceType: "t2.medium"
            iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
            keyName: "laptop"
            subnet:
                id: <SUBNET_IN_AZ2_ID>
```

**Comment by detiber** [comment]
@Sn0rt I haven't tested it, but something similar to below should work for creating the required subnets for us-east-1, given a user that has us-east-1a, us-east-1b, us-east-1c, and us-east-1d availability zones.

```yaml
kind: Cluster
metadata:
  name: my-cluster
spec:
  clusterNetwork:
    services:
    - 10.96.0.0/12
    pods:
    - 192.168.0.0/16
    serviceDomain: cluster.local
  providerSpec:
    value:
      awsprovider/v1alpha1
      kind: AWSClusterProviderSpec
      region: us-east-1
      sshKeyName: default
      networkSpec:
        subnets:
        - availabilityZone: us-east-1a
        - availabilityZone: us-east-1b
        - availabilityZone: us-east-1c
        - availabilityZone: us-east-1d
```
